repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy
