
# cargo-vet config file

[cargo-vet]
version = "0.8"

[policy.haqor-core]
audit-as-crates-io = true

[[exemptions.addr2line]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.adler2]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.anstream]]
version = "0.6.18"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.10"
criteria = "safe-to-deploy"

[[exemptions.anstyle-parse]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.anstyle-wincon]]
version = "3.0.7"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.97"
criteria = "safe-to-deploy"

[[exemptions.async-compression]]
version = "0.4.20"
criteria = "safe-to-deploy"

[[exemptions.atomic-waker]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.74"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.22.1"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.9.0"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.17.0"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.10.1"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.16"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.5.31"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.5.31"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.5.28"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.colorchoice]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.core-foundation]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.core-foundation-sys]]
version = "0.8.7"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.4.2"
criteria = "safe-to-deploy"

[[exemptions.dirs]]
version = "5.0.1"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.displaydoc]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.encoding_rs]]
version = "0.8.35"
criteria = "safe-to-deploy"

[[exemptions.env_filter]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.env_logger]]
version = "0.11.6"
criteria = "safe-to-deploy"

[[exemptions.equivalent]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.10"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.flate2]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.fnv]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.foreign-types]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.foreign-types-shared]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.form_urlencoded]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-executor]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.31.1"
criteria = "safe-to-deploy"

[[exemptions.h2]]
version = "0.4.8"
criteria = "safe-to-deploy"

[[exemptions.haqor-core]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.15.2"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.http-body-util]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.10.1"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.27.5"
criteria = "safe-to-deploy"

[[exemptions.hyper-tls]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.hyper-util]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.icu_collections]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.icu_locid]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.icu_locid_transform]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.icu_locid_transform_data]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.icu_normalizer]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.icu_normalizer_data]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.icu_properties]]
version = "1.5.1"
criteria = "safe-to-deploy"

[[exemptions.icu_properties_data]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.icu_provider]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.icu_provider_macros]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.idna]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.idna_adapter]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.7.1"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.is_terminal_polyfill]]
version = "1.70.1"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.77"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.170"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.litemap]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.26"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.4"
criteria = "safe-to-deploy"

[[exemptions.mime]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.native-tls]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.7"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.20.3"
criteria = "safe-to-deploy"

[[exemptions.openssl]]
version = "0.10.71"
criteria = "safe-to-deploy"

[[exemptions.openssl-macros]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.openssl-probe]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.openssl-sys]]
version = "0.9.106"
criteria = "safe-to-deploy"

[[exemptions.option-ext]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.3.1"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.32"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.94"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.39"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.reqwest]]
version = "0.12.12"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.13"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.24"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.23.23"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.11.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.102.8"
criteria = "safe-to-deploy"

[[exemptions.rustversion]]
version = "1.0.20"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.20"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.27"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.11.1"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.14.0"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.218"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.218"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.140"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.shlex]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.14.0"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.8"
criteria = "safe-to-deploy"

[[exemptions.sqlite]]
version = "0.36.2"
criteria = "safe-to-deploy"

[[exemptions.sqlite3-src]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.sqlite3-sys]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.6.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.99"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.synstructure]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.system-configuration]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.system-configuration-sys]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.18.0"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.69"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.69"
criteria = "safe-to-deploy"

[[exemptions.tinystr]]
version = "0.7.6"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.44.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-native-tls]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.26.2"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.13"
criteria = "safe-to-deploy"

[[exemptions.tower]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.41"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.33"
criteria = "safe-to-deploy"

[[exemptions.try-lock]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.url]]
version = "2.5.4"
criteria = "safe-to-deploy"

[[exemptions.utf16_iter]]
version = "1.0.5"
criteria = "safe-to-deploy"

[[exemptions.utf8_iter]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.utf8parse]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.vcpkg]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.want]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.13.3+wasi-0.2.2"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.50"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.77"
criteria = "safe-to-deploy"

[[exemptions.windows-registry]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.windows-result]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.windows-strings]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.wit-bindgen-rt]]
version = "0.33.0"
criteria = "safe-to-deploy"

[[exemptions.write16]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.writeable]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.yoke]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.yoke-derive]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.zerofrom]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.zerofrom-derive]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.zerovec]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.zerovec-derive]]
version = "0.10.3"
criteria = "safe-to-deploy"
