
# cargo-vet config file

[cargo-vet]
version = "0.8"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.haqor-core]
audit-as-crates-io = true

[[exemptions.addr2line]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.async-compression]]
version = "0.4.20"
criteria = "safe-to-deploy"

[[exemptions.atomic-waker]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.16"
criteria = "safe-to-deploy"

[[exemptions.dirs]]
version = "5.0.1"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.31.1"
criteria = "safe-to-deploy"

[[exemptions.haqor-core]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.27.5"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.77"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.170"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.native-tls]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.7"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.20.3"
criteria = "safe-to-deploy"

[[exemptions.openssl]]
version = "0.10.71"
criteria = "safe-to-deploy"

[[exemptions.openssl-sys]]
version = "0.9.106"
criteria = "safe-to-deploy"

[[exemptions.option-ext]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.32"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.13"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.23.23"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.11.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.102.8"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.27"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.11.1"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.14.0"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.8"
criteria = "safe-to-deploy"

[[exemptions.sqlite]]
version = "0.36.2"
criteria = "safe-to-deploy"

[[exemptions.sqlite3-src]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.sqlite3-sys]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.system-configuration]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.system-configuration-sys]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.18.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.26.2"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.41"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.33"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.utf8parse]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.50"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.77"
criteria = "safe-to-deploy"
