//! Gold-harvested common-noun surface forms (OSHB/morphhb, CC BY 4.0).
//!
//! The noun generator models only segolate and the regular masculine/feminine
//! state+suffix endings; broken/irregular plurals and many construct forms
//! (דִּבְרֵי, יְמֵי, מַלְכֵי, צְבָאוֹת) fall outside it. Rather than model every
//! mishqal, we harvest the attested common-noun surfaces the engine fails on,
//! cantillation-stripped and attested at least twice, each mapped to its
//! lexicon lemma (via the gold Strong's number). Matching stays exact, so these
//! only ever add the correct reading. Besides common nouns the list also carries
//! cardinal numerals and high-frequency adjectives — nominals the generator does
//! not inflect — each mapped to its lexicon lemma.

/// (surface form, lemma, gloss) for attested common nouns the generator cannot
/// produce, sorted by descending corpus frequency.
pub const GOLD_NOUNS: &[(&str, &str, &str)] = &[
    ("עֵינֵי", "עַיִן", "eye; fountain; eye"),
    ("אֱלֹהֶי", "אֱלֹהִים", "gods; God; magistrates"),
    ("צְבָאוֹת", "צָבָא", "mass; army; campaign; hardship; worship"),
    ("מַלְכֵי", "מֶלֶךְ", "king"),
    ("יְמֵי", "יוֹם", "day"),
    ("אֲרוֹן", "אָרוֹן", "box"),
    ("הָרִים", "הַר", "mountain; range"),
    ("עֵינָי", "עַיִן", "eye; fountain; eye"),
    ("אֱמֶת", "אֶמֶת", "stability; certainty; truth; trustworthiness"),
    ("עַבְדֵי", "עֶבֶד", "servant"),
    ("אַמּוֹת", "אַמָּה", "a mother; a cubit; a door-base"),
    ("חָרֶב", "חֶרֶב", "drought; cutting; destructive; knife; sword"),
    ("תּוֹךְ", "תָּוֶךְ", "bisection; centre"),
    ("עֲצֵי", "עֵץ", "tree; wood"),
    ("לַיְלָה", "לַיִל", "twist; night; adversity"),
    ("אֱלֹהַ", "אֱלֹהִים", "gods; God; magistrates"),
    ("צְבָא", "צָבָא", "mass; army; campaign; hardship; worship"),
    ("עָרֶב", "עֶרֶב", "dusk"),
    ("רַגְלָי", "רֶגֶל", "foot; step; pudenda"),
    ("עֲון", "עָוֺן", "perversity; evil"),
    ("חָיִל", "חַיִל", "force; army; wealth; virtue; valor; strength"),
    ("עֹלוֹת", "עֹלָה", "step; holocaust"),
    ("כְלֵי", "כְּלִי", "prepared; apparatus"),
    ("מְלֶאכֶת", "מְלָאכָה", "deputyship; ministry; employment; work; property"),
    ("נַחֲלָת", "נַחֲלָה", "inherited; occupancy; heirloom; estate; patrimony; portion"),
    ("לָיְלָה", "לַיִל", "twist; night; adversity"),
    ("חַצְרֵי", "חָצֵר", "yard; hamlet"),
    ("נִיחֹחַ", "נִיחוֹחַ", "restful; pleasant; delight"),
    ("עוֹלָה", "עֹלָה", "step; holocaust"),
    ("אָהֳלֵי", "אֹהֶל", "tent"),
    ("חֲרוֹן", "חָרוֹן", "burning"),
    ("יָמָי", "יוֹם", "day"),
    ("מִצְותָי", "מִצְוָה", "command; Law"),
    ("אֵילִים", "אַיִל", "strength; strong; chief; ram; pilaster; oak"),
    ("הָרֵי", "הַר", "mountain; range"),
    ("זִבְחֵי", "זֶבַח", "slaughter; flesh; sacrifice"),
    ("מַעַלְלֵי", "מַעֲלָל", "act"),
    ("מַצּוֹת", "מַצָּה", "sweetness; sweet; unfermented cake; Passover"),
    ("נָפֶשׁ", "נֶפֶשׁ", "breathing creature; animal; vitality"),
    ("אֳנִיּוֹת", "אֳנִיָּה", "ship"),
    ("אֹצְרוֹת", "אוֹצָר", "depository"),
    ("חֲצֹצְרוֹת", "חֲצֹצְרָה", "trumpet; sundered"),
    ("מִצְות", "מִצְוָה", "command; Law"),
    ("דִבְרֵי", "דָּבָר", "word; matter; spoken; thing; cause"),
    ("עַוְלָה", "עֶוֶל", "evil"),
    ("יָיִן", "יַיִן", "wine; intoxication"),
    ("קּוֹל", "קוֹל", "voice; sound"),
    ("תוֹלַעַת", "תּוֹלָע", "maggot; voracious; grub"),
    ("חוּצוֹת", "חוּץ", "separate by a wall; outside; outdoors"),
    ("דְרָכָי", "דֶּרֶךְ", "road; trodden; course; mode"),
    ("דַרְכֵי", "דֶּרֶךְ", "road; trodden; course; mode"),
    ("עַצְמוֹת", "עֶצֶם", "bone; strong; body; substance; selfsame"),
    ("חֲיָלִים", "חַיִל", "force; army; wealth; virtue; valor; strength"),
    ("חֲמֹרִים", "חֲמוֹר", "ass; red"),
    ("יַם", "יָם", "sea; large body of water; Mediterranean Sea; large river; artifical basin; west; south"),
    ("רָעוֹת", "רַע", "bad; evil"),
    ("אָבֶן", "אֶבֶן", "stone"),
    ("חָכְמַת", "חׇכְמָה", "wisdom"),
    ("סְבִיבוֹת", "סָבִיב", "circle; neighbour; environs; around"),
    ("עֲטֶרֶת", "עֲטָרָה", "crown"),
    ("עָוֶל", "עֶוֶל", "evil"),
    ("תּוֹעֲבַת", "תּוֹעֵבַה", "disgusting; abhorrence; idolatry; idol"),
    ("אֲרָיוֹת", "אֲרִי", "lion"),
    ("הָבֶל", "הֶבֶל", "emptiness; vanity; transitory; unsatisfactory"),
    ("צָרֵי", "צַר", "narrow; tight; trouble; pebble; opponent; crowding"),
    ("בִגְדֵי", "בֶּגֶד", "covering; clothing; treachery; pillage"),
    ("נְהָרוֹת", "נָהָר", "stream; prosperity"),
    ("רַחֲמִים", "רַחַם", "compassion; womb; cherishing; maiden"),
    ("אֵיל", "אַיִל", "strength; strong; chief; ram; pilaster; oak"),
    ("לֶב", "לֵב", "heart; feelings; will; intellect; centre"),
    ("מֵימֵי", "מַיִם", "water; juice; urine; semen"),
    ("מַמְלָכוֹת", "מַמְלָכָה", "dominion; rule; realm"),
    ("מָתְנָי", "מֹתֶן", "waist; loins"),
    ("אֹתוֹת", "אוֹת", "signal; flag; beacon; monument; omen; prodigy; evidence"),
    ("נְוֵה", "נָוֶה", "at home; lovely; home; den"),
    ("עֲבוֹדַת", "עֲבֹדָה", "work"),
    ("אָרְחוֹת", "אֹרַח", "road; caravan"),
    ("אֻלָם", "אוּלָם", "vestibule"),
    ("חֳרָבוֹת", "חׇרְבָּה", "drought; desolation"),
    ("חָסֶד", "חֶסֶד", "kindness; piety; reproof; beauty"),
    ("חֻקּוֹת", "חֻקָּה", "noun"),
    ("מָסַךְ", "מָסָךְ", "cover; veil"),
    ("קַרְנוֹת", "קֶרֶן", "horn; flask; cornet; elephant's tooth; corner; peak; ray; power"),
    ("תּוֹעֵבָה", "תּוֹעֵבַה", "disgusting; abhorrence; idolatry; idol"),
    ("תּוֹעֵבוֹת", "תּוֹעֵבַה", "disgusting; abhorrence; idolatry; idol"),
    ("אֲתֹנוֹת", "אָתוֹן", "female donkey"),
    ("דָרֶךְ", "דֶּרֶךְ", "road; trodden; course; mode"),
    ("חַיּוֹת", "חַי", "alive; raw; fresh; strong; life"),
    ("יֶרֶךְ", "יָרֵךְ", "thigh; generative parts; shank; flank; side"),
    ("כַנְפֵי", "כָּנָף", "edge; extremity; wing; flap; quarter; pinnacle"),
    ("מְדִינוֹת", "מְדִינָה", "judgeship; jurisdiction; district; region"),
    ("מַטּוֹת", "מַטֶּה", "branch; extending; tribe; rod; correction; sceptre; lance; staff; support"),
    ("מַלְאֲכֵי", "מַלְאָךְ", "messenger; angel"),
    ("נְאוֹת", "נָאָה", "home; pasture"),
    ("עֲצָמוֹת", "עֶצֶם", "bone; strong; body; substance; selfsame"),
    ("עָיִן", "עַיִן", "eye; fountain; eye"),
    ("קַעֲרַת", "קְעָרָה", "bowl; cut"),
    ("תוֹעֲבַת", "תּוֹעֵבַה", "disgusting; abhorrence; idolatry; idol"),
    ("אֱלוֹהַ", "אֱלוֹהַּ", "deity; Deity"),
    ("חֲלֹמוֹת", "חֲלוֹם", "dream"),
    ("חַצְרוֹת", "חָצֵר", "yard; hamlet"),
    ("כָסֶף", "כֶּסֶף", "silver; pale; money"),
    ("מַחְלְקוֹת", "מַחֲלֹקֶת", "section"),
    ("עַרְבֹת", "עֲרָבָה", "desert"),
    ("צָרָי", "צַר", "narrow; tight; trouble; pebble; opponent; crowding"),
    ("אָזְנָי", "אֹזֶן", "broadness; ear"),
    ("חֻצוֹת", "חוּץ", "separate by a wall; outside; outdoors"),
    ("מְזִמּוֹת", "מְזִמָּה", "plan; machination; sagacity"),
    ("מָתְנֵי", "מֹתֶן", "waist; loins"),
    ("מֹאזְנֵי", "מֹאזֵן", "scales"),
    ("מוֹעֲדֵי", "מוֹעֵד", "appointment; time; festival; year; assembly; congregation; place of meeting; signal"),
    ("נֵבֶל", "נֶבֶל", "bag; collapsing; vase; lyre"),
    ("סְעָרָה", "סַעַר", "hurricane"),
    ("עֲבוֹדָה", "עֲבֹדָה", "work"),
    ("פָרִים", "פַּר", "bullock; breaking; dividing"),
    ("רָכֶב", "רֶכֶב", "vehicle; team; cavalry; rider; the upper millstone"),
    ("אוֹצְרוֹת", "אוֹצָר", "depository"),
    ("דְבָרָי", "דָּבָר", "word; matter; spoken; thing; cause"),
    ("חֲזוֹן", "חָזוֹן", "sight; dream; revelation; oracle"),
    ("חֹמָה", "חוֹמָה", "wall"),
    ("יֵין", "יַיִן", "wine; intoxication"),
    ("כוֹכְבֵי", "כּוֹכָב", "star; prince"),
    ("מַמְלְכוּת", "מַמְלָכוּת", "noun"),
    ("עֹנִי", "עֳנִי", "depression; misery"),
    ("רָגֶל", "רֶגֶל", "foot; step; pudenda"),
    ("רוּחוֹת", "רוּחַ", "wind; breath; exhalation; life; anger; unsubstantiality; region of the sky; spirit"),
    ("תּוֹלַעַת", "תּוֹלָע", "maggot; voracious; grub"),
    ("תוֹעֵבָה", "תּוֹעֵבַה", "disgusting; abhorrence; idolatry; idol"),
    ("אֲפִיקֵי", "אָפִיק", "containing; tube; bed; valley; strong; hero"),
    ("אַרְמְנוֹת", "אַרְמוֹן", "citadel; height"),
    ("אָזְנַיִם", "אֹזֶן", "broadness; ear"),
    ("אוֹפַן", "אוֹפָן", "wheel"),
    ("חֶזְוֵי", "חֵזֵו", "sight"),
    ("חָרְבוֹת", "חׇרְבָּה", "drought; desolation"),
    ("עֲנָקִים", "עֲנָקִי", "Anakite"),
    ("עֵינָיִם", "עַיִן", "eye; fountain; eye"),
    ("עַרְבוֹת", "עֲרָבָה", "desert"),
    ("קָבֶר", "קֶבֶר", "sepulchre"),
    ("תִפְאֶרֶת", "תִּפְאָרָה", "ornament"),
    ("אָרֶז", "אֶרֶז", "cedar"),
    ("אוֹצַר", "אוֹצָר", "depository"),
    ("זְרֹעוֹת", "זְרוֹעַ", "arm; stretched; foreleg; force"),
    ("זֵיתִים", "זַיִת", "olive; tree; branch; berry"),
    ("חֶבְלֵי", "חֶבֶל", "rope; line; district; inheritance; noose; company; throe; ruin"),
    ("חֹמוֹת", "חוֹמָה", "wall"),
    ("טָרֶף", "טֶרֶף", "torn; fresh; prey; food"),
    ("יְשׁוּעוֹת", "יְשׁוּעָה", "saved; deliverance; aid; victory; prosperity"),
    ("כֵלִים", "כְּלִי", "prepared; apparatus"),
    ("מִלְחָמוֹת", "מִלְחָמָה", "battle; engagement; war; war-fare"),
    ("מָתְנַיִם", "מֹתֶן", "waist; loins"),
    ("מוֹסְדֵי", "מוֹסָדָה", "foundation"),
    ("נְעָרָי", "נַעַר", "boy; servant; girl"),
    ("נְפָשׁוֹת", "נֶפֶשׁ", "breathing creature; animal; vitality"),
    ("נְתִיבוֹת", "נָתִיב", "track"),
    ("נֵזֶר", "נֶזֶר", "set apart; dedication; locks; chaplet"),
    ("עֲונוֹת", "עָוֺן", "perversity; evil"),
    ("עֲרֵמוֹת", "עָרֵם", "heap; sheaf"),
    ("צְעָקָה", "צַעֲקָה", "shriek"),
    ("צָרוֹת", "צָרָה", "tightness; trouble; rival"),
    ("קִירוֹת", "קִיר", "wall; trench"),
    ("קֶרִי", "קְרִי", "hostile encounter"),
    ("קָדְקֹד", "קׇדְקֹד", "crown; bowed"),
    ("רְכֻשׁ", "רְכוּשׁ", "property"),
    ("רַגְלַיִם", "רֶגֶל", "foot; step; pudenda"),
    ("אֲפִיקִים", "אָפִיק", "containing; tube; bed; valley; strong; hero"),
    ("אֵילֵי", "אַיִל", "strength; strong; chief; ram; pilaster; oak"),
    ("אַלְמָנוֹת", "אַלְמָנָה", "widow; desolate place"),
    ("אֹדוֹת", "אוֹדוֹת", "turnings; occasions; account"),
    ("אֹצָרוֹת", "אוֹצָר", "depository"),
    ("גְבִעִים", "גְּבִיעַ", "goblet; calyx"),
    ("גְבָעוֹת", "גִּבְעָה", "hillock"),
    ("גּוֹרָלוֹת", "גּוֹרָל", "pebble; lot; portion; destiny"),
    ("זְעָקָה", "זַעַק", "shriek; outcry"),
    ("חֲלִיפוֹת", "חֲלִיפָה", "alternation"),
    ("חֲלֵב", "חָלָב", "milk; richness"),
    ("חֲמֻדוֹת", "חָמַד", "delight in"),
    ("חֲרָבוֹת", "חֶרֶב", "drought; cutting; destructive; knife; sword"),
    ("חַוּת", "חַוָּה", "village"),
    ("חַסְדֵי", "חֶסֶד", "kindness; piety; reproof; beauty"),
    ("מְסִלּוֹת", "מְסִלָּה", "thoroughfare; turnpiked; viaduct; staircase"),
    ("מֵיטַב", "מֵיטָב", "best"),
    ("מַחְסֶה", "מַחֲסֶה", "shelter"),
    ("נְבִאִים", "נָבִיא", "prophet; inspired man"),
    ("נְקָמוֹת", "נְקָמָה", "avengement"),
    ("סְבִיבֹתָי", "סָבִיב", "circle; neighbour; environs; around"),
    ("עֲונֹת", "עָוֺן", "perversity; evil"),
    ("עֶגְלֵי", "עֵגֶל", "calf; frisking; steer"),
    ("עֶדְרֵי", "עֵדֶר", "arrangement; muster"),
    ("עֶת", "עֵת", "time; now; when"),
    ("עַצְמוֹתָי", "עֶצֶם", "bone; strong; body; substance; selfsame"),
    ("עָבֶד", "עֶבֶד", "servant"),
    ("קָנִים", "קָנֶה", "reed; erect; rod; shaft; tube; stem; radius; beam"),
    ("רִצְפָה", "רִצְפָּה", "stone; pavement"),
    ("תִפְאָרֶת", "תִּפְאָרָה", "ornament"),
    ("תּוֹכַחַת", "תּוֹכֵחָה", "chastisement; correction; refutation; proof"),
    ("אֶתְמוֹל", "אֶתְמוֹל", "heretofore; yesterday"),
    ("אֹהָלִים", "אֹהֶל", "tent"),
    ("בְרִיחִם", "בְּרִיחַ", "bolt"),
    ("בָטֶן", "בֶּטֶן", "belly; womb; bosom; body"),
    ("חֲטָאֵי", "חֵטְא", "crime; penalty"),
    ("חִידוֹת", "חִידָה", "puzzle; trick; conundrum; maxim"),
    ("חֵל", "חֵיל", "army; intrenchment"),
    ("חֶלְבֵי", "חֶלֶב", "fat; richest; choice"),
    ("חָרֶשׂ", "חֶרֶשׂ", "pottery"),
    ("יֹפִי", "יֳפִי", "beauty"),
    ("כֹהֲנֵי", "כֹּהֵן", "officiating; priest; acting priest"),
    ("לֵילוֹת", "לַיִל", "twist; night; adversity"),
    ("מִכְנְסֵי", "מִכְנָס", "drawers; concealing"),
    ("מַחְמַד", "מַחְמָד", "delightful; a delight"),
    ("נִזְמֵי", "נֶזֶם", "nose-ring"),
    ("נֵדֶר", "נֶדֶר", "promise; thing promised"),
    ("נַפְשׁוֹת", "נֶפֶשׁ", "breathing creature; animal; vitality"),
    ("סוֹפֵר", "סָפַר", "score; inscribe; enumerate; recount; celebrate"),
    ("עֲבֹתֹת", "עֲבֹת", "intwined; string; wreath; foliage"),
    ("עֲגָלוֹת", "עֲגָלָה", "revolving; vehicle"),
    ("עֲלֵי", "עָלֶה", "leaf; foliage"),
    ("עֲצֶרֶת", "עֲצָרָה", "assembly; festival; holiday"),
    ("צֵדָה", "צֵידָה", "food"),
    ("צֻרִים", "צוּר", "cliff; compressed; rock; boulder; refuge; edge; precipitous"),
    ("קִבְרוֹת", "קֶבֶר", "sepulchre"),
    ("קֵצֶה", "קָצֶה", "extremity"),
    ("קַרְנֹת", "קֶרֶן", "horn; flask; cornet; elephant's tooth; corner; peak; ray; power"),
    ("קָרֶת", "קֶרֶת", "city"),
    ("תְאֵנָה", "תְּאֵן", "fig"),
    ("אֲמָרָי", "אֵמֶר", "something said"),
    ("אֲסִירֵי", "אָסִיר", "bound; captive"),
    ("אֲתֹנֹת", "אָתוֹן", "female donkey"),
    ("אוֹצָרוֹת", "אוֹצָר", "depository"),
    ("גֵי", "גַּיְא", "gorge; lofty"),
    ("גָבֶר", "גֶּבֶר", "valiant; warrior; person"),
    ("גָפְרִית", "גׇּפְרִית", "cypress-resin; sulphur"),
    ("גוֹרָלוֹת", "גּוֹרָל", "pebble; lot; portion; destiny"),
    ("דְלָתַיִם", "דֶּלֶת", "something swinging; the valve of a door"),
    ("דַלְתוֹת", "דֶּלֶת", "something swinging; the valve of a door"),
    ("דּוּדָאֵי", "דּוּדַי", "boiler; basket; mandrake"),
    ("הֵיכְלֵי", "הֵיכָל", "palace; temple"),
    ("הוֹלֵלוֹת", "הוֹלֵלָה", "folly"),
    ("זְמִרוֹת", "זָמִיר", "song"),
    ("חֲמָסִים", "חָמָס", "violence; wrong; unjust gain"),
    ("חַחִים", "חָח", "ring"),
    ("חָכְמוֹת", "חׇכְמוֹת", "wisdom"),
    ("יוֹנִים", "יוֹנָה", "dove"),
    ("יוֹצֵר", "יָצַר", "mould; potter; determine"),
    ("כְנָפַיִם", "כָּנָף", "edge; extremity; wing; flap; quarter; pinnacle"),
    ("כּוֹכְבֵי", "כּוֹכָב", "star; prince"),
    ("לֵיל", "לַיִל", "twist; night; adversity"),
    ("מְנֹרָה", "מְנוֹרָה", "chandelier"),
    ("מְתִים", "מַת", "adult; man"),
    ("מַעְיַן", "מַעְיָן", "fountain; source"),
    ("מַעַרְכוֹת", "מַעֲרָכָה", "arrangement; pile; array"),
    ("נִבְלֵי", "נֶבֶל", "bag; collapsing; vase; lyre"),
    ("נֶהִי", "נְהִי", "elegy"),
    ("סְבִיבֹת", "סָבִיב", "circle; neighbour; environs; around"),
    ("סָאתַיִם", "סְאָה", "seah; determinative"),
    ("עֲדָת", "עֵדָה", "assemblage; concourse; family; crowd"),
    ("עֲיָרִים", "עַיִר", "young ass; ass-colt"),
    ("פְתָאיִם", "פְּתִי", "silly"),
    ("פֶתִי", "פְּתִי", "silly"),
    ("צְדָקוֹת", "צְדָקָה", "rightness; rectitude; justice; virtue; prosperity"),
    ("צֳרִי", "צְרִי", "distillation; balsam"),
    ("צַלְעֹת", "צֵלָע", "rib; side; a; timber; plank"),
    ("קְנֵי", "קָנֶה", "reed; erect; rod; shaft; tube; stem; radius; beam"),
    ("קִבְרֵי", "קֶבֶר", "sepulchre"),
    ("קָצֶף", "קֶצֶף", "splinter; rage; strife"),
    ("רְעָדָה", "רַעַד", "shudder"),
    ("רִבְבוֹת", "רְבָבָה", "abundance; myriad"),
    ("רֵחַיִם", "רֵחֶה", "mill"),
    ("רַגְלָיִם", "רֶגֶל", "foot; step; pudenda"),
    ("תוֹכַחַת", "תּוֹכֵחָה", "chastisement; correction; refutation; proof"),
    ("תוֹרִין", "תּוֹר", "bull"),
    ("אֱמוּנִים", "אֵמוּן", "established; trusty; trustworthiness"),
    ("אֲחֹרֵי", "אָחוֹר", "hinder; behind; backward; West"),
    ("אֶתְנָן", "אֶתְנַן", "gift"),
    ("אָלוֹת", "אָלָה", "imprecation"),
    ("אוֹדֹת", "אוֹדוֹת", "turnings; occasions; account"),
    ("גַנּוֹת", "גַּנָּה", "garden"),
    ("הֲלִיכוֹת", "הֲלִיכָה", "walking; procession; march; caravan"),
    ("זְרֹעֹתָי", "זְרוֹעַ", "arm; stretched; foreleg; force"),
    ("זַעֲקַת", "זַעַק", "shriek; outcry"),
    ("חֲלִפוֹת", "חֲלִיפָה", "alternation"),
    ("חֲצִיר", "חָצִיר", "grass; leek"),
    ("חֵי", "חַי", "alive; raw; fresh; strong; life"),
    ("חֶזְיֹנוֹת", "חִזָּיוֹן", "revelation; dream"),
    ("חַיְתוֹ", "חַי", "alive; raw; fresh; strong; life"),
    ("חַלּוֹת", "חַלָּה", "cake; punctured"),
    ("חַרְבוֹת", "חֶרֶב", "drought; cutting; destructive; knife; sword"),
    ("חָבֶר", "חֶבֶר", "society; spell"),
    ("חָלֶד", "חֶלֶד", "life; world"),
    ("חֹתָם", "חוֹתָם", "signature-ring"),
    ("חוֹמוֹת", "חוֹמָה", "wall"),
    ("כָרִים", "כַּר", "ram; battering-ram; meadow; pad; camel's saddle"),
    ("כָרֶם", "כֶּרֶם", "garden; vineyard"),
    ("לְבֻשׁ", "לְבוּשׁ", "garment; wife"),
    ("מְזוּזוֹת", "מְזוּזָה", "door-post; prominent"),
    ("מְנֹרַת", "מְנוֹרָה", "chandelier"),
    ("מְנֹרוֹת", "מְנוֹרָה", "chandelier"),
    ("מִבְצְרֵי", "מִבְצָר", "fortification; castle; fortified; defender"),
    ("מִזְרְקֵי", "מִזְרָק", "bowl"),
    ("מֶלֶך", "מֶלֶךְ", "king"),
    ("מַחְתּוֹת", "מַחְתָּה", "pan"),
    ("מַחֲלָה", "מַחֲלֶה", "sickness"),
    ("מֹאזְנַיִם", "מֹאזֵן", "scales"),
    ("נְעָרוֹת", "נַעֲרָה", "girl"),
    ("נְצִבִים", "נְצִיב", "stationary; prefect; post; statue"),
    ("נַהֲרֵי", "נָהָר", "stream; prosperity"),
    ("נַהֲרוֹת", "נָהָר", "stream; prosperity"),
    ("סִגִים", "סִיג", "scoria"),
    ("סָרִיסִים", "סָרִיס", "eunuch; valet; minister"),
    ("סָרִיסֵי", "סָרִיס", "eunuch; valet; minister"),
    ("סּוֹד", "סוֹד", "session; company; intimacy; consultation; secret"),
    ("עֲבוֹתִים", "עֲבֹת", "intwined; string; wreath; foliage"),
    ("עִנְיַן", "עִנְיָן", "ado; employment; affair"),
    ("עֵצוֹת", "עֵצָה", "advice; plan; prudence"),
    ("עֵרָבוֹן", "עֲרָבוֹן", "pawn"),
    ("עַצְמֹתָי", "עֶצֶם", "bone; strong; body; substance; selfsame"),
    ("עָרְלוֹת", "עׇרְלָה", "prepuce"),
    ("עֹלָמִים", "עוֹלָם", "concealed; vanishing; out of mind; eternity; always"),
    ("עֹפָרֶת", "עוֹפֶרֶת", "lead; dusty"),
    ("עוֹז", "עֹז", "strength; force; security; majesty; praise"),
    ("עוֹלַת", "עֹלָה", "step; holocaust"),
    ("עוֹלֹת", "עֶוֶל", "evil"),
    ("צִבְאוֹת", "צָבָא", "mass; army; campaign; hardship; worship"),
    ("צִדְקוֹת", "צְדָקָה", "rightness; rectitude; justice; virtue; prosperity"),
    ("צֵיד", "צַיִד", "chase; game"),
    ("צַר", "צַר", "narrow; tight; trouble; pebble; opponent; crowding"),
    ("צָהֳרָיִם", "צֹהַר", "light; window; double light; noon"),
    ("צָרָעַת", "צָרַעַת", "leprosy"),
    ("צוּקָה", "צוֹק", "strait; distress"),
    ("קִיא", "קֵא", "vomit"),
    ("קָיִץ", "קַיִץ", "harvest"),
    ("קֹלוֹת", "קוֹל", "voice; sound"),
    ("רְפֻאוֹת", "רְפֻאָה", "medicament"),
    ("אֲגַרְטְלֵי", "אֲגַרְטָל", "basin"),
    ("אֲסִירִים", "אָסִיר", "bound; captive"),
    ("אֲרֻכָה", "אֲרוּכָה", "wholeness"),
    ("אֲתוֹנוֹת", "אָתוֹן", "female donkey"),
    ("אֳרָחוֹת", "אֹרַח", "road; caravan"),
    ("אֶנְקַת", "אֲנָקָה", "shrieking"),
    ("אַגְמֵי", "אֲגַם", "marsh; rush; stockade"),
    ("אָפֶס", "אֶפֶס", "cessation; an end; no further; the ankle; foot"),
    ("אָרֶב", "אֶרֶב", "ambuscade"),
    ("בַהֶרֶת", "בֹּהֶרֶת", "whitish spot on the skin"),
    ("בָגֶד", "בֶּגֶד", "covering; clothing; treachery; pillage"),
    ("גֶחָלִים", "גֶּחֶל", "ember"),
    ("גּוֹרַל", "גּוֹרָל", "pebble; lot; portion; destiny"),
    ("דְלָתוֹת", "דֶּלֶת", "something swinging; the valve of a door"),
    ("הֵרָיוֹן", "הֵרוֹן", "pregnancy"),
    ("זְרוֹע", "זְרוֹעַ", "arm; stretched; foreleg; force"),
    ("זִיקוֹת", "זִיקָה", "leaps; flash; arrow; bond"),
    ("זִמְנִין", "זְמָן", "noun"),
    ("זֵית", "זַיִת", "olive; tree; branch; berry"),
    ("זֹנָה", "זָנָה", "commit adultery; commit idolatry"),
    ("חֲבֵרִים", "חָבֵר", "associate"),
    ("חֲגֹרָה", "חֲגוֹר", "belt"),
    ("חֲלִפֹת", "חֲלִיפָה", "alternation"),
    ("חֲרִצֵי", "חָרִיץ", "incisure; incised; threshing-sledge; slice"),
    ("חֳמָרִם", "חֹמֶר", "bubbling; wave; mire; clay; heap; chomer"),
    ("חֵק", "חֵיק", "bosom"),
    ("חַרְצֻבּוֹת", "חַרְצֻבָּה", "fetter; pain"),
    ("חָפְנֵי", "חֹפֶן", "fist"),
    ("חֹטֶר", "חֹטֵר", "twig"),
    ("טֶפַח", "טֵפַח", "spread of the hand; palm-breadth; corbel"),
    ("טָהֳרַת", "טׇהֳרָה", "purification; purity"),
    ("טָהֳרָה", "טׇהֳרָה", "purification; purity"),
    ("יְתֹמִים", "יָתוֹם", "bereaved"),
    ("יִבְלֵי", "יָבָל", "stream"),
    ("יוֹמָיִם", "יוֹם", "day"),
    ("כְרָעַיִם", "כָּרָע", "leg"),
    ("לַהֶבֶת", "לֶהָבָה", "noun"),
    ("מְעָרוֹת", "מְעָרָה", "cavern"),
    ("מְצָדוֹת", "מְצַד", "fastness"),
    ("מְצֻדַת", "מָצוּד", "net; capture; fastness"),
    ("מְצֻרוֹת", "מְצוּרָה", "hemming; mound; rampart; fortification"),
    ("מִזְרָקוֹת", "מִזְרָק", "bowl"),
    ("מִטּוֹת", "מִטָּה", "bed; sofa; litter; bier"),
    ("מִפְעֲלוֹת", "מִפְעָל", "performance"),
    ("מִצְעֲדֵי", "מִצְעָד", "step; companionship"),
    ("מִקְלְעוֹת", "מִקְלַעַת", "sculpture"),
    ("מֵזַח", "מָזִיחַ", "belt"),
    ("מֵינֶקֶת", "יָנַק", "suck; give milk"),
    ("מַחְלְפוֹת", "מַחְלָפָה", "ringlet of hair"),
    ("מַעְיְנֵי", "מַעְיָן", "fountain; source"),
    ("מַעְיְנֹת", "מַעְיָן", "fountain; source"),
    ("מַעְיָנוֹת", "מַעְיָן", "fountain; source"),
    ("מַעַרְכֹת", "מַעֲרָכָה", "arrangement; pile; array"),
    ("מַצְרֵף", "מִצְרֵף", "crucible"),
    ("מָתְנָיִם", "מֹתֶן", "waist; loins"),
    ("מֹעֲדֵי", "מוֹעֵד", "appointment; time; festival; year; assembly; congregation; place of meeting; signal"),
    ("מוֹסֵרוֹת", "מוֹסֵר", "chastisement; halter; restraint"),
    ("נְדִיבוֹת", "נָדִיב", "voluntary; magnanimous; grandee; tyrant"),
    ("נְדָבוֹת", "נְדָבָה", "spontaneity; spontaneous; spontaneous; abundant"),
    ("נְתִיבָה", "נָתִיב", "track"),
    ("נִדְבוֹת", "נְדָבָה", "spontaneity; spontaneous; spontaneous; abundant"),
    ("נִחֻמִים", "נִחוּם", "consoled; solace"),
    ("נֵפֶל", "נֶפֶל", "fallen; abortion"),
    ("נֶאָצוֹת", "נְאָצָה", "scorn"),
    ("נַעֲלָיִם", "נַעַל", "sandal tongue; sandal; slipper"),
    ("נַעֲרוֹת", "נַעֲרָה", "girl"),
    ("נָבֶל", "נֶבֶל", "bag; collapsing; vase; lyre"),
    ("נֹאדוֹת", "נֹאד", "bag"),
    ("סְאִים", "סְאָה", "seah; determinative"),
    ("סְעָרוֹת", "סַעַר", "hurricane"),
    ("סִבְכֵי", "סְבָךְ", "copse"),
    ("סֵמֶל", "סֶמֶל", "likeness"),
    ("סַעֲרַת", "סַעַר", "hurricane"),
    ("סֹפְרֵי", "סָפַר", "score; inscribe; enumerate; recount; celebrate"),
    ("עֲדֵי", "עַד", "terminus; duration; advance; perpetuity"),
    ("עֲלִלוֹת", "עֲלִילָה", "exploit; performance; opportunity"),
    ("עֲצָמָי", "עֶצֶם", "bone; strong; body; substance; selfsame"),
    ("עֲרֵמַת", "עָרֵם", "heap; sheaf"),
    ("עֲרָבוֹת", "עֲרָבָה", "desert"),
    ("עֵינֹת", "עַיִן", "eye; fountain; eye"),
    ("עֶדִי", "עֲדִי", "finery; outfit; headstall"),
    ("עֶזְרָת", "עֶזְרָה", "aid"),
    ("עַרְבֵי", "עָרָב", "willow"),
    ("עָבוֹת", "עָב", "envelope; darkness; density; cloud; copse"),
    ("עָווֹן", "עָוֺן", "perversity; evil"),
    ("עָרְלַת", "עׇרְלָה", "prepuce"),
    ("עֻגַת", "עֻגָּה", "ashcake; round"),
    ("עֻגָה", "עֻגָּה", "ashcake; round"),
    ("עֻגוֹת", "עֻגָּה", "ashcake; round"),
    ("עוֹלֵלֹת", "עֹלֵלָה", "gleanings; gleaning-time"),
    ("עוֹלָל", "עוֹלֵל", "suckling"),
    ("עוֹלָלִים", "עוֹלֵל", "suckling"),
    ("פֶרִי", "פְּרִי", "fruit"),
    ("פָרֹכֶת", "פֹּרֶכֶת", "separatrix; screen"),
    ("פָרוֹת", "פָּרָה", "heifer"),
    ("צְלָעוֹת", "צֵלָע", "rib; side; a; timber; plank"),
    ("צִלְצַל", "צְלָצַל", "clatter; whirring; cricket; harpoon; rattling; cymbal; clanging"),
    ("צִמּוּקִים", "צַמּוּק", "cake of dried grapes"),
    ("צִנּוֹת", "צִנָּה", "hook; pointed; shield; prickliness; cold; piercing"),
    ("צִפְעוֹנִי", "צֶפַע", "viper; thrusting; hissing"),
    ("צֶאֱלִים", "צֶאֶל", "lotus tree"),
    ("צָיִד", "צַיִד", "chase; game"),
    ("צָרֶבֶת", "צָרֶבֶת", "conflagration"),
    ("קְבֻרַת", "קְבוּרָה", "sepulture; sepulchre"),
    ("קְנָאֹת", "קִנְאָה", "jealousy; envy"),
    ("קִיטֹר", "קִיטוֹר", "fume; cloud"),
    ("קִלְלַת", "קְלָלָה", "vilification"),
    ("קִמּוֹשׂ", "קִמּוֹשׁ", "prickly"),
    ("קָרֶן", "קֶרֶן", "horn; flask; cornet; elephant's tooth; corner; peak; ray; power"),
    ("רְבִבִים", "רָבִיב", "rain; accumulation"),
    ("רִב", "רִיב", "contest"),
    ("רִישׁ", "רֵישׁ", "poverty"),
    ("רַעֲבוֹן", "רְעָבוֹן", "famine"),
    ("רֹתֶם", "רֶתֶם", "Spanish broom"),
    ("רֻחוֹת", "רוּחַ", "wind; breath; exhalation; life; anger; unsubstantiality; region of the sky; spirit"),
    ("שׁוֹפָרוֹת", "שׁוֹפָר", "cornet; clear"),
    ("תְבוּנוֹת", "תָּבוּן", "intelligence; argument; caprice"),
    ("תְהֹמֹת", "תְּהוֹם", "abyss; deep"),
    ("תְהֹמוֹת", "תְּהוֹם", "abyss; deep"),
    ("תַחְרָא", "תַּחֲרָא", "corslet; white; hollow"),
    ("תַחֲלֻאִים", "תַּחֲלוּא", "malady"),
    ("תּוֹך", "תָּוֶךְ", "bisection; centre"),
    ("תּוֹכָחוֹת", "תּוֹכֵחָה", "chastisement; correction; refutation; proof"),
    ("תּוֹלֵעָה", "תּוֹלָע", "maggot; voracious; grub"),
    ("תּוֹעֲבֹת", "תּוֹעֵבַה", "disgusting; abhorrence; idolatry; idol"),
    ("תּוֹצְאֹת", "תּוֹצָאָה", "exit; boundary; deliverance; source"),
    ("תוֹכָחוֹת", "תּוֹכֵחָה", "chastisement; correction; refutation; proof"),
    // Cardinal numerals and high-frequency adjectives. The lexicon carries these
    // as nominals (pos 'a'), but the generator models neither the numeral mishqal
    // (אַחַת, עֶשְׂרֵה, חֲמִשָּׁה, מָאתַיִם) nor the geminate/III-vav adjective plurals
    // (רַבִּים, חַיִּים, גְּדוֹלָה). Harvested exact surfaces, lemma + gloss from gold.
    ("רַבִּים", "רַב", "abundant"),
    ("אַחַת", "אֶחָד", "united; one; first"),
    ("עֶשְׂרֵה", "עָשָׂר", "ten; -teen; -teenth"),
    ("חֲמִשָּׁה", "חָמֵשׁ", "five"),
    ("חַיִּים", "חַי", "alive; raw; fresh; strong; life"),
    ("אֲחֵרִים", "אַחֵר", "hinder; next; other"),
    ("אַרְבָּעָה", "אַרְבַּע", "four"),
    ("אָלֶף", "אֶלֶף", "thousand"),
    ("זִקְנֵי", "זָקֵן", "old"),
    ("עֲשָׂרָה", "עֶשֶׂר", "ten"),
    ("גְדוֹלָה", "גָּדוֹל", "great; older; insolent"),
    ("מָאתַיִם", "מֵאָה", "hundred"),
    ("שְׁתַּיִם", "שְׁנַיִם", "two; twofold"),
    ("חֲמֵשׁ", "חָמֵשׁ", "five"),
    ("עֲשֶׂרֶת", "עֶשֶׂר", "ten"),
    ("אֶחָת", "אֶחָד", "united; one; first"),
    ("חֲכָמִים", "חָכָם", "wise"),
    ("אַלְפַּיִם", "אֶלֶף", "thousand"),
    ("חֲלָלִים", "חָלָל", "pierced; polluted"),
    ("זָרִים", "זוּר", "strange; foreign; profane"),
    ("אַחַד", "אֶחָד", "united; one; first"),
    ("חַיָּה", "חַי", "alive; raw; fresh; strong; life"),
    ("גְּדֹלוֹת", "גָּדוֹל", "great; older; insolent"),
    ("תְּמִימִם", "תָּמִים", "entire; integrity; truth"),
    ("חֲמֵשֶׁת", "חָמֵשׁ", "five"),
    ("גְּדוֹלָה", "גָּדוֹל", "great; older; insolent"),
    ("חַלְלֵי", "חָלָל", "pierced; polluted"),
    ("חֲזָקָה", "חָזָק", "strong; hard; bold; violent"),
    ("שֵׁשֶׁת", "שֵׁשׁ", "six; sixth"),
    ("גְּדֹלִים", "גָּדוֹל", "great; older; insolent"),
    ("רָעִים", "רַע", "bad; evil"),
    ("גְדֹלָה", "גָּדוֹל", "great; older; insolent"),
    ("רַעֲנָן", "רַעֲנָן", "verdant; new; prosperous"),
    ("קְדֹשִׁים", "קָדוֹשׁ", "sacred; God; angel; saint; sanctuary"),
    ("יְקָרָה", "יָקָר", "valuable"),
    ("אַרְבַּעַת", "אַרְבַּע", "four"),
    ("אַחֶרֶת", "אַחֵר", "hinder; next; other"),
    ("עֲרֵלִים", "עָרֵל", "exposed; uncircumcised"),
    ("דַּלִּים", "דַּל", "dangling; weak; thin"),
    ("שְׁנָיִם", "שְׁנַיִם", "two; twofold"),
    ("אַלְפֵי", "אֶלֶף", "thousand"),
    ("יִרְאֵי", "יָרֵא", "fearing; reverent"),
    ("רְחוֹקָה", "רָחוֹק", "remote; precious"),
    ("עֲנָוִים", "עָנָו", "depressed; gentle; needy; saintly"),
    ("חֲדָשִׁים", "חָדָשׁ", "new"),
    ("נָכְרִיּוֹת", "נׇכְרִי", "strange; foreign; non-relative; different"),
    ("נָכְרִיָּה", "נׇכְרִי", "strange; foreign; non-relative; different"),
    ("טְמֵאָה", "טָמֵא", "foul"),
    ("קְטַנָּה", "קָטָן", "abbreviated; diminutive"),
    ("עֲקָרָה", "עָקָר", "sterile"),
    ("יְפֵה", "יָפֶה", "beautiful"),
    ("עָרִיצִים", "עָרִיץ", "fearful; powerful; tyrannical"),
    ("אַחֲרֹנִים", "אַחֲרוֹן", "hinder; late; last; western"),
    ("תִּשְׁעָה", "תֵּשַׁע", "nine; ninth"),
    ("תַּחְתִּיּוֹת", "תַּחְתִּי", "lowermost; depths; pit; womb"),
    ("שְׁמֹנַת", "שְׁמֹנֶה", "eight; eighth"),
    ("טוֹבַת", "טוֹב", "good"),
    ("רִאשֹׁנָה", "רִאשׁוֹן", "first"),
    ("נְקִיִּם", "נָקִי", "innocent"),
    ("שְׁתָּיִם", "שְׁנַיִם", "two; twofold"),
    // Suffixed common nouns the generator's regular state+suffix model misses
    // (broken/reduced stems, III-vav/III-aleph, segolate suffix bases). Bare
    // attested surfaces; proclitics are peeled by the parser.
    ("מִגְרָשֶׁהָ", "מִגְרָשׁ", "suburb; area around a building"),
    ("כִּסְאוֹ", "כִּסֵּא", "covered; throne; canopied"),
    ("עֲונָם", "עָוֺן", "perversity; evil"),
    ("לִבֶּךָ", "לֵב", "heart; feelings; will; intellect; centre"),
    ("זַרְעֲךָ", "זֶרַע", "seed; fruit; plant; sowing-time; posterity"),
    ("מִצְותָיו", "מִצְוָה", "command; Law"),
    ("מִצְותֶיךָ", "מִצְוָה", "command; Law"),
    ("חַטָּאתוֹ", "חַטָּאָה", "offence; penalty; occasion; sacrifice"),
    ("מִצְותַי", "מִצְוָה", "command; Law"),
    ("חֵילוֹ", "חַיִל", "force; army; wealth; virtue; valor; strength"),
    ("בַּדָּיו", "בַּד", "separation; part; branch; bar; chief"),
    ("רוּחוֹ", "רוּחַ", "wind; breath; exhalation; life; anger"),
    ("רָחְבּוֹ", "רֹחַב", "width"),
    ("רָעָתָם", "רַע", "bad; evil"),
    ("חֻקֶּיךָ", "חֹק", "enactment; appointment"),
    ("נִזְרוֹ", "נֶזֶר", "set apart; dedication; locks; chaplet"),
    ("נַפְשֹׁתֵיכֶם", "נֶפֶשׁ", "breathing creature; animal; vitality"),
    ("מַעֲשֶׂיךָ", "מַעֲשֶׂה", "action; transaction; activity; product"),
    ("לְבָבֶךָ", "לֵבָב", "heart"),
    ("מַלְכֵיהֶם", "מֶלֶךְ", "king"),
    ("שָׂרָיו", "שַׂר", "head"),
    ("מַחֲלֻקְתּוֹ", "מַחֲלֹקֶת", "section"),
    ("רִכְבּוֹ", "רֶכֶב", "vehicle; team; cavalry; rider"),
    ("פִּרְיוֹ", "פְּרִי", "fruit"),
    ("עֶרְכְּךָ", "עֵרֶךְ", "pile; equipment; estimate"),
    ("מַעֲשֵׂהוּ", "מַעֲשֶׂה", "action; transaction; activity; product"),
    ("יְמִינֶךָ", "יָמִין", "right; stronger; south"),
    ("עֵדֹתֶיךָ", "עֵדָה", "testimony"),
    ("אֲמָתֶךָ", "אָמָה", "maid-servant"),
    ("אָהֳלוֹ", "אֹהֶל", "tent"),
    ("חַטָּאתִי", "חַטָּאָה", "offence; penalty; occasion; sacrifice"),
    ("בִּגְדוֹ", "בֶּגֶד", "covering; clothing; treachery; pillage"),
    ("קַרְנֹתָיו", "קֶרֶן", "horn; flask; cornet; corner; peak; ray; power"),
    ("פִּרְיָהּ", "פְּרִי", "fruit"),
    ("מַעַלְלֵיהֶם", "מַעֲלָל", "act"),
    ("שָׂרֶיהָ", "שַׂר", "head"),
    ("צִדְקֶךָ", "צֶדֶק", "right; equity; prosperity"),
    ("רָחְבָּהּ", "רֹחַב", "width"),
    ("מִשְׁמַרְתִּי", "מִשְׁמֶרֶת", "watch; custody; sentry; post"),
    ("חֻקּוֹתַי", "חֻקָּה", "statute; ordinance"),
    ("עָנְיִי", "עֳנִי", "depression; misery"),
    ("שִׁכְמוֹ", "שְׁכֶם", "neck; spur"),
    ("קֹמָתוֹ", "קוֹמָה", "height"),
    ("נֵרֹתֶיהָ", "נִיר", "lamp; light"),
    ("עֲונוֹ", "עָוֺן", "perversity; evil"),
    ("מַעֲשָׂיו", "מַעֲשֶׂה", "action; transaction; activity; product"),
    ("אֵידָם", "אֵיד", "oppression; misfortune; ruin"),
    ("כַּנְפֵיהֶם", "כָּנָף", "edge; extremity; wing; flap; quarter"),
    ("הֲמוֹנָהּ", "הָמוֹן", "noise; tumult; crowd; disquietude; wealth"),
    ("קֹלוֹ", "קוֹל", "voice; sound"),
    ("מִקְנֵיהֶם", "מִקְנֶה", "bought; property; stock; acquisition"),
    ("לַחְמוֹ", "לֶחֶם", "food; bread; grain"),
    ("מַרְאֵהוּ", "מַרְאֶה", "view; appearance"),
    ("מֶמְשַׁלְתּוֹ", "מֶמְשָׁלָה", "rule; realm; ruler"),
    ("מַעַלְלֵיכֶם", "מַעֲלָל", "act"),
    ("כְּבוֹדֶךָ", "כָּבוֹד", "weight; splendor; copiousness"),
    ("מַעֲשֵׂיהֶם", "מַעֲשֶׂה", "action; transaction; activity; product"),
    ("שַׁבְּתוֹתַי", "שַׁבָּת", "intermission; Sabbath"),
    ("עֲונֵךְ", "עָוֺן", "perversity; evil"),
    ("רַחֲמֶיךָ", "רַחַם", "compassion; womb; cherishing; maiden"),
    ("רָעָתִי", "רַע", "bad; evil"),
    ("מְלַאכְתּוֹ", "מְלָאכָה", "deputyship; ministry; employment; work"),
    ("עֲונִי", "עָוֺן", "perversity; evil"),
    ("מַמְלַכְתּוֹ", "מַמְלָכָה", "dominion; rule; realm"),
    ("דִּבְרֵיכֶם", "דָּבָר", "word; matter; spoken; thing; cause"),
    ("מַטֵּהוּ", "מַטֶּה", "branch; extending; tribe; rod; correction"),
    ("מוֹשְׁבֹתֵיכֶם", "מוֹשָׁב", "seat; site; session; abode; population"),
    ("חֻקָּיו", "חֹק", "enactment; appointment"),
    ("מְקֹמוֹ", "מָקוֹם", "standing; spot; condition"),
    ("חֶלְבּוֹ", "חֶלֶב", "fat; richest; choice"),
    ("מַחֲנֵיהֶם", "מַחֲנֶה", "encampment; army"),
    ("אָהֳלֵיהֶם", "אֹהֶל", "tent"),
    ("מֵימָיו", "מַיִם", "water; juice; urine; semen"),
    ("בִטְנְךָ", "בֶּטֶן", "belly; womb; bosom; body"),
    ("אִמְרָתֶךָ", "אִמְרָה", "word; speech; command"),
    ("מְשִׁיחוֹ", "מָשִׁיחַ", "anointed; consecrated; Messiah"),
    ("נָוֵהוּ", "נָוֶה", "at home; lovely; home; den"),
    ("מָתְנָיו", "מֹתֶן", "waist; loins"),
    ("מִשְׂגַּבִּי", "מִשְׂגָּב", "cliff; lofty; inaccessible; altitude; refuge"),
    ("אַרְמְנוֹתֶיהָ", "אַרְמוֹן", "citadel; height"),
    ("אֲמִתֶּךָ", "אֶמֶת", "stability; certainty; truth; trustworthiness"),
    ("עֻזּוֹ", "עֹז", "strength; force; security; majesty; praise"),
    ("שִׁנָּיו", "שֵׁן", "tooth; sharp; ivory; cliff"),
    ("עֵדְותֶיךָ", "עֵדוּת", "testimony"),
    ("שָׂדֵהוּ", "שָׂדֶה", "field"),
    ("מִקְנֵהוּ", "מִקְנֶה", "bought; property; stock; acquisition"),
    ("יְרֵכוֹ", "יָרֵךְ", "thigh; generative parts; shank; flank; side"),
    ("טַפָּם", "טַף", "family"),
    ("אַדְמַתְכֶם", "אֲדָמָה", "soil"),
    ("לְשֹׁנוֹ", "לָשׁוֹן", "tongue"),
    ("אֲמָתוֹ", "אָמָה", "maid-servant"),
    ("אֲמָתְךָ", "אָמָה", "maid-servant"),
    ("כֵּלֶיהָ", "כְּלִי", "prepared; apparatus"),
    ("חַטָּאתָם", "חַטָּאָה", "offence; penalty; occasion; sacrifice"),
    ("אֲשָׁמוֹ", "אָשָׁם", "guilt; fault; sin-offering"),
    ("נִבְלָתָם", "נְבֵלָה", "flabby; carcase; carrion; idol"),
    ("חַטֹּאתָם", "חַטָּאָה", "offence; penalty; occasion; sacrifice"),
    ("פִּשְׁעֵיהֶם", "פֶּשַׁע", "revolt"),
    ("עֻלְּכֶם", "עֹל", "yoke"),
    ("דַּרְכֵיכֶם", "דֶּרֶךְ", "road; trodden; course; mode"),
    ("מַחֲנֵהוּ", "מַחֲנֶה", "encampment; army"),
    ("צָרָיו", "צַר", "narrow; tight; trouble; opponent"),
    ("צֹאנֶךָ", "צֹאן", "flock"),
    ("נִבְלָתוֹ", "נְבֵלָה", "flabby; carcase; carrion; idol"),
    ("בַּעְלָהּ", "בַּעַל", "master; husband; owner"),
    ("תֹצְאֹתָיו", "תּוֹצָאָה", "exit; boundary; deliverance; source"),
    // Plain common nouns the generator misses: broken plurals, duals, segolate
    // constructs, directional (locale) he forms, and variant spellings.
    ("יָמָּה", "יָם", "sea; large body of water; west"),
    ("עִזִּים", "עֵז", "she-goat"),
    ("חַטָּאת", "חַטָּאָה", "offence; penalty; occasion; sacrifice"),
    ("צָפוֹנָה", "צָפוֹן", "hidden; dark; north"),
    ("שָׁקֶר", "שֶׁקֶר", "untruth; sham"),
    ("אִשֶּׁה", "אִשָּׁה", "burnt-offering; sacrifice"),
    ("מִזְרָחָה", "מִזְרָח", "sunrise; east"),
    ("קָדָשִׁים", "קֹדֶשׁ", "sacred; sanctity"),
    ("עֵשֶׂב", "עֶשֶׂב", "grass"),
    ("קָרְבַּן", "קׇרְבָּן", "brought near; present"),
    ("כֶּתֶף", "כָּתֵף", "shoulder; side-piece"),
    ("נֶגְבָּה", "נֶגֶב", "south; Negeb"),
    ("עֶשְׂרֹנִים", "עִשָּׂרוֹן", "tenth"),
    ("פָּרָשִׁים", "פָּרָשׁ", "steed; driver; cavalry"),
    ("חִטִּים", "חִטָּה", "wheat"),
    ("קָדִימָה", "קָדִים", "fore; East; eastward; east wind"),
    ("שָׁמֶן", "שֶׁמֶן", "grease; richness"),
    ("אִיִּים", "אִי", "habitable spot; dry land; coast; island"),
    ("מַחְשְׁבוֹת", "מַחֲשָׁבָה", "contrivance; intention; plan"),
    ("דְּמֵי", "דָּם", "blood; juice; bloodshed"),
    ("טַבְּעֹת", "טַבַּעַת", "seal; signet; ring"),
    ("חַטֹּאות", "חַטָּאָה", "offence; penalty; occasion; sacrifice"),
    ("תֵּימָנָה", "תֵּימָן", "south; right"),
    ("חַטַּאת", "חַטָּאָה", "offence; penalty; occasion; sacrifice"),
    ("עַתֻּדִים", "עַתּוּד", "prepared; full grown; he-goats; leaders"),
    ("מִזְבְּחוֹת", "מִזְבֵּחַ", "altar"),
    ("מֵישָׁרִים", "מֵישָׁר", "evenness; prosperity; concord; straightness"),
    ("פִּשְׁעֵי", "פֶּשַׁע", "revolt"),
    ("מַחֲשָׁבוֹת", "מַחֲשָׁבָה", "contrivance; intention; plan"),
    ("מִשְׁפְּטֵי", "מִשְׁפָּט", "verdict; sentence; law; justice; right"),
    ("מַעֲשֵׂי", "מַעֲשֶׂה", "action; transaction; activity; product"),
    ("צָפֹנָה", "צָפוֹן", "hidden; dark; north"),
    ("זִכָּרוֹן", "זִכְרוֹן", "memento"),
    ("סַמִּים", "סַם", "aroma"),
    ("יַרְכְּתֵי", "יְרֵכָה", "flank; rear; recess"),
    ("שֵׂכֶל", "שֶׂכֶל", "intelligence; success"),
    ("תַּהְפֻּכוֹת", "תַּהְפֻּכָה", "perversity; fraud"),
    ("גְּמַלִּים", "גָּמָל", "camel"),
    ("חוּצָה", "חוּץ", "separate by a wall; outside; outdoors"),
    ("אַמָּתַיִם", "אַמָּה", "a mother; a cubit; a door-base"),
    ("מוֹשַׁב", "מוֹשָׁב", "seat; site; session; abode; population"),
    ("מִזְבְּחֹת", "מִזְבֵּחַ", "altar"),
    ("אִסָּר", "אֱסָר", "obligation; vow"),
    ("חֻקִּים", "חֹק", "enactment; appointment"),
    ("פִּנּוֹת", "פִּנָּה", "angle; pinnacle; chieftain"),
    ("פַּלְגֵי", "פֶּלֶג", "rill"),
    ("דְּגֵי", "דָּג", "fish"),
    ("מַטְעַמִּים", "מַטְעַם", "delicacy"),
    ("יָמִימָה", "יוֹם", "day"),
    ("ימֵי", "יוֹם", "day"),
    // Long-tail harvest: lower-frequency attested nouns/adjectives the
    // generator misses (broken plurals, suffix bases, irregular constructs).
    ("גָּבֹהַ", "גָּבֹהַּ", "elevated; powerful; arrogant"),
    ("עֲנִיֵּי", "עָנִי", "depressed"),
    ("עִוְרִים", "עִוֵּר", "blind"),
    ("צַדִּיקִם", "צַדִּיק", "just"),
    ("אֲחֵרוֹת", "אַחֵר", "hinder; next; other"),
    ("עֲקֻדִּים", "עָקֹד", "striped"),
    ("נְקֻדִּים", "נָקֹד", "spotted"),
    ("רַחֲבַת", "רָחָב", "roomy"),
    ("תְּמִימָה", "תָּמִים", "entire; integrity; truth"),
    ("רִאשֹׁנִים", "רִאשׁוֹן", "first"),
    ("חַדָּה", "חַד", "sharp"),
    ("עֲנִיִּים", "עָנִי", "depressed"),
    ("חָפְשִׁים", "חׇפְשִׁי", "exempt"),
    ("אֲחָדִים", "אֶחָד", "united; one; first"),
    ("אֲבִיר", "אָבִיר", "mighty"),
    ("חַכְמֵי", "חָכָם", "wise"),
    ("גְּדֹלֹת", "גָּדוֹל", "great; older; insolent"),
    ("גְבֹהָה", "גָּבֹהַּ", "elevated; powerful; arrogant"),
    ("קְרֹבִים", "קָרוֹב", "near"),
    ("גִּבֹּרִים", "גִּבּוֹר", "powerful; warrior; tyrant"),
    ("גְּדוֹלִים", "גָּדוֹל", "great; older; insolent"),
    ("רֵקִים", "רֵיק", "empty; worthless"),
    ("יְקָרוֹת", "יָקָר", "valuable"),
    ("קְרוֹבָה", "קָרוֹב", "near"),
    ("אֱוִלִים", "אֱוִיל", "silly"),
    ("עֲיֵפָה", "עָיֵף", "languid"),
    ("עָרִיצֵי", "עָרִיץ", "fearful; powerful; tyrannical"),
    ("נָאוָה", "נָאוֶה", "suitable; beautiful"),
    ("גִּבֹּרֵי", "גִּבּוֹר", "powerful; warrior; tyrant"),
    ("עֲצַבֵּיהֶם", "עָצָב", "image"),
    ("חָכְמָתֶךָ", "חׇכְמָה", "wisdom"),
    ("יְמֵיהֶם", "יוֹם", "day"),
    ("מָתְנֶיךָ", "מֹתֶן", "waist; loins"),
    ("לִבֵּנוּ", "לֵב", "heart; feelings; will; intellect; centre"),
    ("לַחְמָם", "לֶחֶם", "food; bread; grain"),
    ("נַחֲלָתֶךָ", "נַחֲלָה", "inherited; occupancy; heirloom; estate; "),
    ("סְבִיבָיו", "סָבִיב", "circle; neighbour; environs; around"),
    ("חֶלְקוֹ", "חֵלֶק", "smoothness; allotment"),
    ("עֲמָלוֹ", "עָמָל", "toil; wearing effort; worry"),
    ("תּוֹרָתֶךָ", "תּוֹרָה", "precept; statute; Decalogue; Pentateuch"),
    ("דַּלְתֹתָיו", "דֶּלֶת", "something swinging; the valve of a door"),
    ("זַרְעֲכֶם", "זֶרַע", "seed; fruit; plant; sowing-time; posteri"),
    ("צָרֶיךָ", "צַר", "narrow; tight; trouble; pebble; opponent"),
    ("חֲמֹרוֹ", "חֲמוֹר", "ass; red"),
    ("צַוָּארֶךָ", "צַוָּאר", "neck; bound"),
    ("חֲלֹמוֹ", "חֲלוֹם", "dream"),
    ("סְבִיבֹתֶיהָ", "סָבִיב", "circle; neighbour; environs; around"),
    ("עֲמָלִי", "עָמָל", "toil; wearing effort; worry"),
    ("כְּלֵיהֶם", "כְּלִי", "prepared; apparatus"),
    ("אַמְתַּחְתּוֹ", "אַמְתַּחַת", "expansive; bag"),
    ("רַחֲמָיו", "רַחַם", "compassion; womb; cherishing; maiden"),
    ("בִּרְכָּיו", "בֶּרֶךְ", "knee"),
    ("טַפְּכֶם", "טַף", "family"),
    ("לַחְמְךָ", "לֶחֶם", "food; bread; grain"),
    ("עַמֻּדֵיהֶם", "עַמּוּד", "column; standing; stand"),
    ("חֶצְיוֹ", "חֵצִי", "half; middle"),
    ("עֲונָהּ", "עָוֺן", "perversity; evil"),
    ("חַטֹּאתֵיכֶם", "חַטָּאָה", "offence; penalty; occasion; sacrifice; e"),
    ("דְּמֵיהֶם", "דָּם", "blood; juice; bloodshed"),
    ("עֲונֹתֵיכֶם", "עָוֺן", "perversity; evil"),
    ("שִׁבְטֵיכֶם", "שֵׁבֶט", "scion; stick; clan"),
    ("סְבִיבוֹתֵיכֶם", "סָבִיב", "circle; neighbour; environs; around"),
    ("אַדְמָתֶךָ", "אֲדָמָה", "soil"),
    ("זְרֹעוֹ", "זְרוֹעַ", "arm; stretched; foreleg; force"),
    ("כִּסְאֲךָ", "כִּסֵּא", "covered; throne; canopied"),
    ("חֶפְצוֹ", "חֵפֶץ", "pleasure; desire; valuable; matter"),
    ("חָלְיוֹ", "חֳלִי", "malady; anxiety; calamity"),
    ("שָׂרֵיהֶם", "שַׂר", "head"),
    ("קוֹלֶךָ", "קוֹל", "voice; sound"),
    ("צָרֵינוּ", "צַר", "narrow; tight; trouble; pebble; opponent"),
    ("רָעָתֵךְ", "רַע", "bad; evil"),
    ("דָּלִיּוֹתָיו", "דָּלִיָּה", "dangling; bough"),
    ("עֻזָּהּ", "עֹז", "strength; force; security; majesty; prai"),
    ("צָרֵיהֶם", "צַר", "narrow; tight; trouble; pebble; opponent"),
    ("מְשִׁיחֶךָ", "מָשִׁיחַ", "anointed; consecrated; Messiah"),
    ("תְּהִלָּתֶךָ", "תְּהִלָּה", "laudation; hymn"),
    ("עֻזֶּךָ", "עֹז", "strength; force; security; majesty; prai"),
    ("עֻזְּךָ", "עֹז", "strength; force; security; majesty; prai"),
    ("יִשְׁעֵנוּ", "יֶשַׁע", "liberty; deliverance; prosperity"),
    ("שַׁעֲשֻׁעָי", "שַׁעְשֻׁעַ", "enjoyment"),
    ("עָמְדָם", "עֹמֶד", "spot"),
    ("חֶלְקָם", "חֵלֶק", "smoothness; allotment"),
    ("גְּבִרְתָּהּ", "גְּבֶרֶת", "mistress"),
    ("מוֹלַדְתִּי", "מוֹלֶדֶת", "nativity; lineage; native country; offsp"),
    ("רַחְמָהּ", "רֶחֶם", "womb"),
    ("יַלְדֵיהֶן", "יֶלֶד", "something born; lad; offspring"),
    ("סְבִיבֹתֵיהֶם", "סָבִיב", "circle; neighbour; environs; around"),
    ("שְׂמֹאלוֹ", "שְׂמֹאול", "dark; enveloped; north; left"),
    ("אֹתֹתַי", "אוֹת", "signal; flag; beacon; monument; omen; pr"),
    ("מַטְּךָ", "מַטֶּה", "branch; extending; tribe; rod; correctio"),
    ("קִרְבּוֹ", "קֶרֶב", "nearest; center"),
    ("קְצוֹתָיו", "קָצָה", "termination"),
    ("חַטַּאתְכֶם", "חַטָּאָה", "offence; penalty; occasion; sacrifice; e"),
    ("אֶצְבָּעוֹ", "אֶצְבַּע", "sieze; finger; toe"),
    ("זִבְחֵיהֶם", "זֶבַח", "slaughter; flesh; sacrifice"),
    ("שָׂדְךָ", "שָׂדֶה", "field"),
    ("עֲמִיתֶךָ", "עָמִית", "companionship; comrade"),
    ("נִדְרֵיכֶם", "נֶדֶר", "promise; thing promised"),
    ("מִשְׁפַּחְתּוֹ", "מִשְׁפָּחָה", "family; circle of relatives; class; spec"),
    ("נִסְכּוֹ", "נֶסֶךְ", "libation; cast idol"),
    ("בִּגְדֵיהֶם", "בֶּגֶד", "covering; clothing; treachery; pillage"),
    ("טַעְמוֹ", "טַעַם", "taste; perception; intelligence; mandate"),
    ("לַחְמֵנוּ", "לֶחֶם", "food; bread; grain"),
    ("שִׁמְעֲךָ", "שֵׁמַע", "heard; sound; rumor; announcement; audie"),
    ("מַעְשְׂרֹתֵיכֶם", "מַעֲשֵׂר", "tenth; tithe"),
    ("סְבִיבֹתֵינוּ", "סָבִיב", "circle; neighbour; environs; around"),
    ("פָּעֳלוֹ", "פֹּעַל", "act; work"),
    ("יֵינָם", "יַיִן", "wine; intoxication"),
    ("אָזְנָיו", "אֹזֶן", "broadness; ear"),
    ("עֲצָתוֹ", "עֵצָה", "advice; plan; prudence"),
    ("מֵעָיו", "מֵעֶה", "intestines; abdomen; sympathy; vest; sto"),
    ("מָגִנִּי", "מָגֵן", "shield; protector; hide"),
    ("סְבִיבֹתָיו", "סָבִיב", "circle; neighbour; environs; around"),
    ("יִשְׁעֶךָ", "יֶשַׁע", "liberty; deliverance; prosperity"),
    ("תְּאֵנָתוֹ", "תְּאֵן", "fig"),
    ("מִזְבַּחֲךָ", "מִזְבֵּחַ", "altar"),
    ("עֻלֵּנוּ", "עֹל", "yoke"),
    ("כֹּהֲנָיו", "כֹּהֵן", "officiating; priest; acting priest"),
    ("מִזְבְּחֹתָיו", "מִזְבֵּחַ", "altar"),
    ("חַרְבוֹתָם", "חֶרֶב", "drought; cutting; destructive; knife; sw"),
    ("חִצָּיו", "חֵץ", "piercer; arrow; wound; bolt; shaft"),
    ("זַעְמוֹ", "זַעַם", "froth; fury"),
    ("סַחְרָהּ", "סַחַר", "profit"),
    ("אַרְמְנֹתֶיהָ", "אַרְמוֹן", "citadel; height"),
    ("עֶדְרוֹ", "עֵדֶר", "arrangement; muster"),
    ("עֲצָתִי", "עֵצָה", "advice; plan; prudence"),
    ("מֵעֶיךָ", "מֵעֶה", "intestines; abdomen; sympathy; vest; sto"),
    ("תִפְאַרְתֵּךְ", "תִּפְאָרָה", "ornament"),
    ("מִשְׁכְּבוֹתָם", "מִשְׁכָּב", "bed; bier; sleep; intercourse"),
    ("פִּשְׁעָם", "פֶּשַׁע", "revolt"),
    ("צִמְחָהּ", "צֶמַח", "sprout"),
    ("אָהֳלִי", "אֹהֶל", "tent"),
    ("מִזְבְּחוֹתֵיכֶם", "מִזְבֵּחַ", "altar"),
    ("מִזְבְּחוֹתָם", "מִזְבֵּחַ", "altar"),
    ("מִבְטַחוֹ", "מִבְטָח", "refuge; security; assurance"),
    ("שָׁרָשָׁיו", "שֶׁרֶשׁ", "root"),
    ("עָמְדִי", "עָמַד", "stand"),
    ("תּוֹעֲבֹתָיִךְ", "תּוֹעֵבַה", "disgusting; abhorrence; idolatry; idol"),
    ("רִשְׁתִּי", "רֶשֶׁת", "net; catching"),
    ("אֲגַפָּיו", "אַגָּף", "wings of an army; crowds of troops"),
    ("עֲלִילוֹתָם", "עֲלִילָה", "exploit; performance; opportunity"),
    ("נְעוּרָיִךְ", "נָעוּר", "youth; juvenility; young"),
    ("יָפְיֵךְ", "יֳפִי", "beauty"),
    ("כֹּהֲנֶיהָ", "כֹּהֵן", "officiating; priest; acting priest"),
    ("חוֹמוֹתַיִךְ", "חוֹמָה", "wall"),
    ("חֵילֶךָ", "חַיִל", "force; army; wealth; virtue; valor; stre"),
    ("סְבִיבוֹתָיו", "סָבִיב", "circle; neighbour; environs; around"),
    ("מַחְלְקוֹתָם", "מַחֲלֹקֶת", "section"),
    ("חִצֶּיךָ", "חֵץ", "piercer; arrow; wound; bolt; shaft"),
    ("עֲלִילוֹתָיו", "עֲלִילָה", "exploit; performance; opportunity"),
    ("תַּחֲנוּנָי", "תַּחֲנוּן", "prayer"),
    ("עַצְמוֹתָיו", "עֶצֶם", "bone; strong; body; substance; selfsame"),
    ("צִדְקָתֶךָ", "צְדָקָה", "rightness; rectitude; justice; virtue; p"),
    ("תוֹרָתֶךָ", "תּוֹרָה", "precept; statute; Decalogue; Pentateuch"),
    ("כְּרֻבִים", "כְּרוּב", "cherub; imaginary figure"),
    ("קָשֶׁת", "קֶשֶׁת", "bow; strength; iris"),
    ("שִׁקֻּץ", "שִׁקּוּץ", "disgusting; filthy; idolatrous; idol"),
    ("צִיִּים", "צִי", "ship; fixture"),
    ("פַּעֲמָיִם", "פַּעַם", "stroke"),
    ("טַבָּעֹת", "טַבַּעַת", "seal; sunk; signet; ring"),
    ("שָׁקֶל", "שֶׁקֶל", "weight"),
    ("פִּגְרֵי", "פֶּגֶר", "carcase; idolatrous image"),
    ("חַטֹּאת", "חַטָּאָה", "offence; penalty; occasion; sacrifice; expiat"),
    ("כַּנְפוֹת", "כָּנָף", "edge; extremity; wing; flap; quarter; pinnacl"),
    ("נְשִׂאִים", "נָשִׂיא", "exalted; king; sheik; mist"),
    ("צִצִּים", "צִיץ", "glistening; plate; flower; bright; wing; glea"),
    ("מָגִנִּים", "מָגֵן", "shield; protector; hide"),
    ("קָשֶׁר", "קֶשֶׁר", "alliance"),
    ("פִשְׁתִּים", "פִּשְׁתֶּה", "linen; carded"),
    ("תְּשֻׁאוֹת", "תְּשֻׁאָה", "crashing; clamor"),
    ("גַּעֲרַת", "גְּעָרָה", "chiding"),
    ("שְׁפָיִים", "שְׁפִי", "bareness; bare"),
    ("בִּרְכַּיִם", "בֶּרֶךְ", "knee"),
    ("שְׁפָיִם", "שְׁפִי", "bareness; bare"),
    ("שְׁרִרוּת", "שְׁרִירוּת", "obstinacy"),
    ("אֻמִּים", "לְאֹם", "community"),
    ("אוֹיֵב", "אֹיֵב", "enemy"),
    ("אֹיְבֶיךָ", "אֹיֵב", "enemy"),
    ("תוֹכָם", "תָּוֶךְ", "midst"),
    ("מִזְבֵּחָה", "מִזְבֵּחַ", "altar"),
    ("דֹרֹתֵיכֶם", "דּוֹר", "generation"),
    ("אֱלָהָא", "אֱלָהּ", "God (Aramaic)"),
    ("אֹיְבֵיהֶם", "אֹיֵב", "enemy"),
    ("עֵדֻת", "עֵדוּת", "testimony"),
    ("חַצְרֵיהֶן", "חָצֵר", "court; enclosure"),
    ("יְמָנִית", "יְמָנִי", "right (side)"),
];
