//! Curated irregular-verb surfaces harvested from the OSHB/morphhb gold tagging
//! (CC BY 4.0, Strong-keyed), restricted to the verb **stems the algorithmic
//! generator does not model** — Polel, Polal, Hithpolel, Poel, Pilpel,
//! Hithpalpel, Hishtaphel and the other rare/geminate-base binyanim
//! ([`super::verb::Binyan`] only covers the seven productive stems). These
//! forms cannot be produced by reversing a triliteral paradigm, so — exactly as
//! [`super::irregular_noun`] does for suppletive nouns — we list every attested
//! surface and match it exactly. Matching is gold-precise, so these only ever
//! add the correct reading; they never displace a generated analysis.
//!
//! Each entry is `(surface, root, binyan, form, pgn)` where `surface` is the
//! cantillation-normalised full token (proclitics included, as it appears in
//! the text) and `binyan`/`form`/`pgn` are rendered the same way the generator
//! labels its own analyses, so downstream consumers treat them uniformly.

use std::collections::HashMap;

/// One harvested irregular-verb reading. A surface may have several (homographs
/// / form ambiguity), so the lookup keys a surface to a list of these.
#[derive(Debug, Clone, Copy)]
pub struct IrregularVerb {
    pub surface: &'static str,
    pub root: &'static str,
    pub binyan: &'static str,
    pub form: &'static str,
    pub pgn: &'static str,
}

/// Build a surface → readings lookup over [`IRREGULAR_VERBS`] and
/// [`IRREGULAR_VOCALIZATIONS`].
pub fn lookup() -> HashMap<&'static str, Vec<&'static IrregularVerb>> {
    let mut m: HashMap<&'static str, Vec<&'static IrregularVerb>> = HashMap::new();
    for v in IRREGULAR_VERBS.iter().chain(IRREGULAR_VOCALIZATIONS) {
        m.entry(v.surface).or_default().push(v);
    }
    m
}

/// Attested forms of the *modeled* stems (Qal/Niphal/Piel/…) whose vocalization
/// the algorithmic generator does not produce — hapax / anomalous / doubly-weak
/// spellings (euphonic dagesh חָדֵלּוּ, the doubly-weak צוה contraction לְצַוּת,
/// the segol שְׁאֶלְתֶּם, etc.). Like [`IRREGULAR_VERBS`] these are gold-precise
/// full-surface matches that only ever add the correct reading; they exist for
/// the downstream product (the accuracy harness measures the generator and
/// excludes these gizra='Irregular' rows, so they never inflate it).
pub const IRREGULAR_VOCALIZATIONS: &[IrregularVerb] = &[
    IrregularVerb {
        // Euphonic dagesh forte in C3 (Judg 5:6-7); generator builds חָדֵלוּ.
        surface: "חָדֵלּוּ",
        root: "חדל",
        binyan: "Qal",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        // Geminate המם "rout" Qal wayyiqtol + 3mp suffix with anomalous u-theme
        // host yəhummēm (וַיְהֻמֵּם, Exod 14:24 etc.); generator reads it as Pual.
        surface: "וַיְהֻמֵּם",
        root: "הממ",
        binyan: "Qal",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        // C2-aleph segol theme before the heavy afformative; generator: שְׁאַלְתֶּם.
        surface: "שְׁאֶלְתֶּם",
        root: "שאל",
        binyan: "Qal",
        form: "Perfect",
        pgn: "2mp",
    },
    IrregularVerb {
        // Archaic/Aramaic-flavoured imperative (Isa 21:12,14).
        surface: "אֵתָיוּ",
        root: "אתה",
        binyan: "Qal",
        form: "Imperative",
        pgn: "2mp",
    },
    IrregularVerb {
        // Anomalous patah-retaining + dagesh construct participle (Isa 23:8-9).
        surface: "נִכְבַּדֵּי",
        root: "כבד",
        binyan: "Niphal",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        // Niphal perfect with o-theme (גאל II "defile", Lam 4:14).
        surface: "נְגֹאֲלוּ",
        root: "גאל",
        binyan: "Niphal",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        // Doubly-weak III-he + C2-vav Piel infinitive construct (with ל), צוה.
        surface: "לְצַוּת",
        root: "צוה",
        binyan: "Piel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        // Doubly-weak Piel participle + 2ms suffix -ekkā, צוה.
        surface: "מְצַוֶּךָּ",
        root: "צוה",
        binyan: "Piel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        // III-he/aleph Piel imperfect 2mp (תאה "mark out", Num 34:7-8).
        surface: "תְּתָאוּ",
        root: "תאה",
        binyan: "Piel",
        form: "Imperfect",
        pgn: "2mp",
    },
    IrregularVerb {
        // Qal vocalization of ערמ "be crafty" (1 Sam 23:22); generator reads it
        // only as Hiphil.
        surface: "יַעְרִם",
        root: "ערמ",
        binyan: "Qal",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        // Wayyiqtol of חלק "divide" + 3mp suffix: segol preformative with a
        // qamats (qamats-hatuf) under the C1 guttural (1 Chr 23-24); generator
        // builds the patah-prefix וַיַּחַלְקֵם.
        surface: "וַיֶּחָלְקֵם",
        root: "חלק",
        binyan: "Qal",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        // Qal imperfect of רדף "pursue" + 2ms suffix: anomalous dagesh + hataf-
        // patah under C2 dalet (יִרְדֲּפֶךָ, Ezek 35:6).
        surface: "יִרְדֲּפֶךָ",
        root: "רדף",
        binyan: "Qal",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        // Hollow שית "set" Qal perfect 2ms + 1cs suffix: patah + dageshed tav
        // host šatt- (שַׁתַּנִי, Ps 88:7).
        surface: "שַׁתַּנִי",
        root: "שית",
        binyan: "Qal",
        form: "Perfect",
        pgn: "2ms",
    },
    IrregularVerb {
        // Stative I-guttural imperative 2mp, pausal qamats theme (ʾehāḇû אֱהָבוּ,
        // Zech 8:17,19); generator builds the segol אֶהֱבוּ.
        surface: "אֱהָבוּ",
        root: "אהב",
        binyan: "Qal",
        form: "Imperative",
        pgn: "2mp",
    },
    IrregularVerb {
        // Qal imperfect 1cs of בחר, secondary hataf-patah under the non-guttural
        // C1 (אֶבֲחַר, Job 34:4,33); generator builds the silent-sheva אֶבְחַר.
        surface: "אֶבֲחַר",
        root: "בחר",
        binyan: "Qal",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        // Geminate Qal imperfect 1cs of תמם with a tsere-yod preformative
        // (אֵיתָם, Hos 5:9 etc.); not produced by the geminate builder.
        surface: "אֵיתָם",
        root: "תמם",
        binyan: "Qal",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        // Piel cohortative 1cs of לקט with a qamats-qatan theme (אֲלַקֳטָה,
        // Ruth 2:2,7); generator builds the sheva/tsere אֲלַקְּטָה.
        surface: "אֲלַקֳטָה",
        root: "לקט",
        binyan: "Piel",
        form: "Cohortative",
        pgn: "1cs",
    },
    IrregularVerb {
        // III-He Hophal perfect 3fs of עלה, holam preformative + hataf-patah
        // guttural (הֹעֲלָתָה, Nah 2:8); generator builds the qamats-hatuf הׇעְלָתָה.
        surface: "הֹעֲלָתָה",
        root: "עלה",
        binyan: "Hophal",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        // III-He Hophal perfect 2ms of ראה (הָרְאֵתָ, Deut 4:35).
        surface: "הָרְאֵתָ",
        root: "ראה",
        binyan: "Hophal",
        form: "Perfect",
        pgn: "2ms",
    },
    IrregularVerb {
        // III-ayin Hiphil perfect 2ms of ידע, patah under the guttural + plain
        // tav (הוֹדַעַתָ, 1 Sam 28:15); generator builds הוֹדַעְתָּ.
        surface: "הוֹדַעַתָ",
        root: "ידע",
        binyan: "Hiphil",
        form: "Perfect",
        pgn: "2ms",
    },
    IrregularVerb {
        // Stative Qal imperative 2fs of חרב, qamats-hatuf theme (חֳרָבִי,
        // Jer 50:21 etc.); generator builds חִרְבִי.
        surface: "חֳרָבִי",
        root: "חרב",
        binyan: "Qal",
        form: "Imperative",
        pgn: "2fs",
    },
    IrregularVerb {
        // Hollow רום Niphal imperfect 3mp with euphonic dagesh in C3 mem
        // (יֵרוֹמּוּ, Ps 89:17 etc.); generator builds the single-mem יֵרוֹמוּ.
        surface: "יֵרוֹמּוּ",
        root: "רום",
        binyan: "Niphal",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        // Denominal ימן "go to the right" Hiphil participle mp, yod kept
        // consonantal (מַיְמִינִים, 1 Chr 12:2); generator contracts it.
        surface: "מַיְמִינִים",
        root: "ימן",
        binyan: "Hiphil",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        // Hithpolel of הלל "praise/boast" (OSHB-tagged Hithpael), o-stem
        // reduplicated base the generator's Hithpael doesn't model (Ps 5:6 etc.).
        surface: "יִתְהֹלְלוּ",
        root: "הלל",
        binyan: "Hithpael",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        // Qamats-theme spelling of the same Hithpolel (יִתְהֹלָלוּ, Jer 46:9 etc.).
        surface: "יִתְהֹלָלוּ",
        root: "הלל",
        binyan: "Hithpael",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        // Hithpolel of מלל "languish" (OSHB-tagged Hithpael), o-stem base
        // (יִתְמֹלָלוּ, Ps 58:8).
        surface: "יִתְמֹלָלוּ",
        root: "מלל",
        binyan: "Hithpael",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        // Noun-like Qal infinitive construct of יכל "be able" (Num 14:16).
        surface: "יְכֹלֶת",
        root: "יכל",
        binyan: "Qal",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        // III-guttural Hithpael imperfect, theme qamats before furtive ʿayin
        // (Prov 18:1); generator builds the regular patah יִתְגַּלַּע.
        surface: "יִתְגַּלָּע",
        root: "גלע",
        binyan: "Hithpael",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        // II-guttural Hithpael imperfect compensatory variant (נחם); generator
        // builds the regular virtual-doubling יִתְנַחֵם.
        surface: "יִתְנֶחָם",
        root: "נחם",
        binyan: "Hithpael",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        // III-he/aleph Qal participle of נשא II "lend on interest" (creditor),
        // segol theme written with final aleph (Deut 24:11 etc.).
        surface: "נֹשֶׁא",
        root: "נשא",
        binyan: "Qal",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        // Geminate Qal imperfect 3fs, poetic energic spelling (Prov 1:20, 8:3).
        surface: "תָּרֹנָּה",
        root: "רננ",
        binyan: "Qal",
        form: "Imperfect",
        pgn: "3fs",
    },
    IrregularVerb {
        // Hothpaal-style census form, qamats + no doubling (Num 1:47 etc.);
        // generator builds the regular doubled הִתְפַּקְּדוּ.
        surface: "הִתְפָּקְדוּ",
        root: "פקד",
        binyan: "Hithpael",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        // Hollow/II-aleph Qal participle "those who despise" (Ezek 28:24,26).
        surface: "הַשָּׁאטִים",
        root: "שאט",
        binyan: "Qal",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        // Qal participle fp of אתה "the things to come" (Isa 41:23, 44:7).
        surface: "הָאֹתִיּוֹת",
        root: "אתה",
        binyan: "Qal",
        form: "Participle (act.)",
        pgn: "fp",
    },
    IrregularVerb {
        // Paragogic-he on a 3fs wayyiqtol of עגב (Ezek 23:3).
        surface: "וַתַּעְגְּבָה",
        root: "עגב",
        binyan: "Qal",
        form: "Wayyiqtol",
        pgn: "3fs",
    },
    IrregularVerb {
        // Doubly-weak pe-nun + consonantal-he Hiphil imperfect, mappiq
        // (נגה "illumine", 2 Sam 22:29).
        surface: "יַגִּיהַּ",
        root: "נגה",
        binyan: "Hiphil",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        // Doubly-weak pe-yod + III-he Qal infinitive construct (ירה "shoot",
        // with ל; 1 Sam 20:36, 2 Chr 35:23).
        surface: "לִירוֹת",
        root: "ירה",
        binyan: "Qal",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        // Apocopated III-he Qal jussive "may he have dominion" (Ps 72:8), final
        // sheva + dagesh.
        surface: "וְיֵרְדְּ",
        root: "רדה",
        binyan: "Qal",
        form: "Jussive",
        pgn: "3ms",
    },
    IrregularVerb {
        // Pe-yod Qal perfect 2fs with holam theme, וְיֹלַדְתְּ (Gen 16:11, Judg 13:5,7).
        surface: "וְיֹלַדְתְּ",
        root: "ילד",
        binyan: "Qal",
        form: "Perfect",
        pgn: "2fs",
    },
    IrregularVerb {
        // Apocopated III-he Qal wayyiqtol "and he took captive" (Num 21:1).
        surface: "וַיִּשְׁבְּ",
        root: "שבה",
        binyan: "Qal",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        // Defectively-pointed וַיֹּאמְרוּ (medial sheva omitted in the text).
        surface: "וַיֹּאמרוּ",
        root: "אמר",
        binyan: "Qal",
        form: "Wayyiqtol",
        pgn: "3mp",
    },
    IrregularVerb {
        // III-he Qal imperative 2ms with a-vowels, אָרָה "pluck" (Ps 80:13, Song 5:1).
        surface: "אָרָה",
        root: "ארה",
        binyan: "Qal",
        form: "Imperative",
        pgn: "2ms",
    },
    IrregularVerb {
        // Geminate Hiphil imperfect 1cs "I will do harm" (רעע); generator reads
        // it otherwise.
        surface: "אָרַע",
        root: "רעע",
        binyan: "Hiphil",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        // Contracted I-aleph Hiphil imperfect 1cs "I will gather" (אסף, the two
        // alephs merging; Mic 4:6, Zeph 1:2).
        surface: "אֹסֵף",
        root: "אסף",
        binyan: "Hiphil",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        // Pual fp participle construct with irregular de-gemination (קצע
        // "corner", with ל; Ezek 46:22) — not the regular doubled מְקֻצְּעֹת.
        surface: "לִמְקֻצְעֹת",
        root: "קצע",
        binyan: "Pual",
        form: "Participle (act.)",
        pgn: "fp",
    },
    IrregularVerb {
        // Lengthened (paragogic-he) Hiphil imperative, î-grade (יטב; Ps 36:11,
        // Isa 23:16) — the rare emphatic imperative the generator omits.
        surface: "הֵיטִיבָה",
        root: "יטב",
        binyan: "Hiphil",
        form: "Imperative",
        pgn: "2ms",
    },
    IrregularVerb {
        // Aramaic-flavoured Hiphil imperative 2mp of אתה "bring" (Isa 21:14).
        surface: "הֵתָיוּ",
        root: "אתה",
        binyan: "Hiphil",
        form: "Imperative",
        pgn: "2mp",
    },
    IrregularVerb {
        // Geminate Hiphil perfect 3cp "they blossomed" (נצץ; Song 6:11, 7:13).
        surface: "הֵנֵצוּ",
        root: "נצצ",
        binyan: "Hiphil",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        // Apocopated III-he Qal wayyiqtol 1cp "and we were" (היה; Num 13:33).
        surface: "וַנְּהִי",
        root: "היה",
        binyan: "Qal",
        form: "Wayyiqtol",
        pgn: "1cp",
    },
    IrregularVerb {
        // III-he Piel perfect 3ms "he rebuked / grew dim" (כהה; 1 Sam 3:13).
        surface: "כֵּהָה",
        root: "כהה",
        binyan: "Piel",
        form: "Perfect",
        pgn: "3ms",
    },
    IrregularVerb {
        // Pual participle ms "polished/burnished" (מרט, with ו; 1 Kgs 7:45).
        surface: "וּמוֹרָט",
        root: "מרט",
        binyan: "Pual",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        // Hollow Niphal participle ms "discerning" (בין, with ו; Gen 41:33,39).
        surface: "וּנְבוֹן",
        root: "בינ",
        binyan: "Niphal",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        // Qamats-grade Hiphil infinitive absolute "abundantly" (רבה; Amos 4:9)
        // beside the usual הַרְבֵּה.
        surface: "הַרְבָּה",
        root: "רבה",
        binyan: "Hiphil",
        form: "Inf. Absolute",
        pgn: "",
    },
];

/// Attested unmodeled-stem verb surfaces, harvested from gold (see module docs).
pub const IRREGULAR_VERBS: &[IrregularVerb] = &[
    IrregularVerb {
        surface: "אֲכַלְכֵּל",
        root: "כול",
        binyan: "Pilpel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "אֲצַפְצֵף",
        root: "צפפ",
        binyan: "Pilpel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "אֲקוֹמֵם",
        root: "לבב",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "אֲרוֹמְמֶךָּ",
        root: "רומ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "אֲרוֹמִמְךָ",
        root: "רומ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "אֲרוֹמִמְךָ",
        root: "רומ",
        binyan: "Polel",
        form: "Cohortative",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "אֲשׂוֹחֵחַ",
        root: "שיח",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "אֵרוֹמָם",
        root: "רומ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "אֶשְׁתַּחֲוֶה",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "אֶשְׁתַּעֲשָׁע",
        root: "שעע",
        binyan: "Hithpalpel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "אֶשְׁתּוֹלְלוּ",
        root: "שלל",
        binyan: "Hithpolel",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "אֶתְבּוֹנֵן",
        root: "בינ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "אֶתְבּוֹנָן",
        root: "בינ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "אֶתְקוֹטָט",
        root: "קוט",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "אֶתְרוֹעָע",
        root: "רוע",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "אֻמְלְלָה",
        root: "אמל",
        binyan: "Pulal",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "אֻמְלְלוּ",
        root: "אמל",
        binyan: "Pulal",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "אֻמְלָל",
        root: "אמל",
        binyan: "Pulal",
        form: "Perfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "אֻמְלָלָה",
        root: "אמל",
        binyan: "Pulal",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "אֻמְלָלוּ",
        root: "אמל",
        binyan: "Pulal",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "בְּהִשְׁתַּחֲוָיָתִי",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "בְּסַּאסְּאָה",
        root: "",
        binyan: "Pilpel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "בּוֹשַׁסְכֶם",
        root: "בשס",
        binyan: "Poel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "הִסְתּוֹפֵף",
        root: "ספפ",
        binyan: "Hithpoel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "הִשְׁתַּחֲוֵיתִי",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "הִתְבֹּנַנְתָּ",
        root: "בינ",
        binyan: "Hithpolel",
        form: "Perfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "הִתְבּוֹנְנוּ",
        root: "בינ",
        binyan: "Hithpolel",
        form: "Imperative",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "הִתְבּוֹנָן",
        root: "בינ",
        binyan: "Hithpolel",
        form: "Perfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "הִתְבּוֹנָנוּ",
        root: "בינ",
        binyan: "Hithpolel",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "הִתְגַּלְגָּלוּ",
        root: "גלל",
        binyan: "Hithpalpel",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "הִתְמַהְמְהָם",
        root: "מהה",
        binyan: "Hithpalpel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "הִתְמַהְמְהוּ",
        root: "מהה",
        binyan: "Hithpalpel",
        form: "Imperative",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "הִתְמַהְמָהְנוּ",
        root: "מהה",
        binyan: "Hithpalpel",
        form: "Perfect",
        pgn: "1cp",
    },
    IrregularVerb {
        surface: "הִתְמַהְמָהְתִּי",
        root: "מהה",
        binyan: "Hithpalpel",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "הִתְמֹגָגוּ",
        root: "מוג",
        binyan: "Hithpolel",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "הִתְמוֹטְטָה",
        root: "מוט",
        binyan: "Hithpolel",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "הִתְפּוֹרְרָה",
        root: "פרר",
        binyan: "Hithpolel",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "הִתְקַלְקָלוּ",
        root: "קלל",
        binyan: "Hithpalpel",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "הִתְקוֹשְׁשׁוּ",
        root: "קשש",
        binyan: "Hithpolel",
        form: "Imperative",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "הִתְרֹעֲעָה",
        root: "רעע",
        binyan: "Hithpolel",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "הִתְרֹעָעִי",
        root: "רוע",
        binyan: "Hithpolel",
        form: "Imperative",
        pgn: "2fs",
    },
    IrregularVerb {
        surface: "הַמְצַפְצְפִים",
        root: "צפפ",
        binyan: "Pilpel",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        surface: "הַמְשֹׁרֲרִים",
        root: "שיר",
        binyan: "Polel",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        surface: "הָתְפָּקְדוּ",
        root: "פקד",
        binyan: "Hothpaal",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "הֻטַּמָּאָה",
        root: "טמא",
        binyan: "Hothpaal",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "וְאֶשְׁתַּחֲוֶה",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וְאֶשְׁתַּעֲשַׁע",
        root: "שעע",
        binyan: "Hithpalpel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וְאֶשְׁתּוֹמֵם",
        root: "שממ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וְגִלְגַּלְתִּיךָ",
        root: "גלל",
        binyan: "Pilpel",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וְדוֹמַמְתִּי",
        root: "דממ",
        binyan: "Polel",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וְהִשְׁתַּחֲוִיתֶם",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Perfect",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "וְהִשְׁתַּחֲוִיתָ",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Perfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "וְהִשְׁתַּחֲוֵיתִי",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וְהִשְׁתַּחֲוּוּ",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "וְהִתְאֹשָׁשׁוּ",
        root: "אשש",
        binyan: "Hithpolel",
        form: "Imperative",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "וְהִתְבּוֹנְנוּ",
        root: "בינ",
        binyan: "Hithpolel",
        form: "Imperative",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "וְהִתְבּוֹנֵן",
        root: "בינ",
        binyan: "Hithpolel",
        form: "Imperative",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "וְהִתְבּוֹנַנְתָּ",
        root: "בינ",
        binyan: "Hithpolel",
        form: "Perfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "וְהִתְגֹּעֲשׁוּ",
        root: "געש",
        binyan: "Hithpolel",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "וְהִתְהֹלְלוּ",
        root: "הלל",
        binyan: "Hithpolel",
        form: "Imperative",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "וְהִתְהֹלָלוּ",
        root: "הלל",
        binyan: "Hithpolel",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "וְהִתְחוֹלֵל",
        root: "חול",
        binyan: "Hithpolel",
        form: "Imperative",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "וְהִתְנוֹדְדָה",
        root: "נוד",
        binyan: "Hithpolel",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "וְהִתְעֹרַרְתִּי",
        root: "עור",
        binyan: "Hithpolel",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וְהִתְשׁוֹטַטְנָה",
        root: "שוט",
        binyan: "Hithpolel",
        form: "Imperative",
        pgn: "2fp",
    },
    IrregularVerb {
        surface: "וְהַמְשֹׁרְרִים",
        root: "שיר",
        binyan: "Polel",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        surface: "וְהַמְשֹׁרֲרִים",
        root: "שיר",
        binyan: "Polel",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        surface: "וְהַמְשׁוֹרֲרִים",
        root: "שיר",
        binyan: "Polel",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        surface: "וְטֵאטֵאתִיהָ",
        root: "",
        binyan: "Pilpel",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וְיִכּוֹנָנוּ",
        root: "כונ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וְיִשְׁתַּחֲוּוּ",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Jussive",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וְיִשְׁתַּחֲוּוּ",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וְיִתְבּוֹנְנוּ",
        root: "בינ",
        binyan: "Hithpolel",
        form: "Jussive",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וְיִתְלֹנָן",
        root: "לונ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וְיִתְמַרְמַר",
        root: "מרר",
        binyan: "Hithpalpel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וְיִתְרוֹמֵם",
        root: "רומ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וְכִלְכַּלְתִּי",
        root: "כול",
        binyan: "Pilpel",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וְלַמְשֹׁרֲרִים",
        root: "שיר",
        binyan: "Polel",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        surface: "וְנִוַּסְּרוּ",
        root: "יסר",
        binyan: "Nithpael",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "וְנִכַּפֵּר",
        root: "כפר",
        binyan: "Nithpael",
        form: "Perfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וְנִשְׁתַּחֲוֶה",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Imperfect",
        pgn: "1cp",
    },
    IrregularVerb {
        surface: "וְנוֹדַד",
        root: "נדד",
        binyan: "Poal",
        form: "Perfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וְסִכְסַכְתִּי",
        root: "סוכ",
        binyan: "Pilpel",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וְעֹלַלְתִּי",
        root: "עלל",
        binyan: "Poel",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וְקַרְקַר",
        root: "קור",
        binyan: "Pilpel",
        form: "Perfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וְקֹשְׁשׁוּ",
        root: "קשש",
        binyan: "Poel",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "וְקוֹנְנוּ",
        root: "קינ",
        binyan: "Polel",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "וְקוֹנְנוּהָ",
        root: "קינ",
        binyan: "Polel",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "וְשֹׁבַבְתִּיךָ",
        root: "שוב",
        binyan: "Polel",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וְשׁוֹבַבְתִּיךָ",
        root: "שוב",
        binyan: "Polel",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וְתִכּוֹנֵן",
        root: "כונ",
        binyan: "Hithpolel",
        form: "Jussive",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "וִיבֹקְקוּ",
        root: "בקק",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וִיסוֹבְבוּ",
        root: "סבב",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וִירֹמְמוּהוּ",
        root: "רומ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וִירוֹמִמְךָ",
        root: "רומ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַאֲמֹתְתֵהוּ",
        root: "מות",
        binyan: "Polel",
        form: "Wayyiqtol",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וַאֲסֹבְבָה",
        root: "סבב",
        binyan: "Poel",
        form: "Cohortative",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וַאֲסוֹבְבָה",
        root: "סבב",
        binyan: "Poel",
        form: "Cohortative",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וַאֲרֹמְמֶנְהוּ",
        root: "רומ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וַיְזוֹרֵר",
        root: "זרר",
        binyan: "Poel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיְכַלְכְּלֵם",
        root: "כול",
        binyan: "Pilpel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיְכַלְכֵּל",
        root: "כול",
        binyan: "Pilpel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיְכֹנְנֶךָ",
        root: "כונ",
        binyan: "Polel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיְכֻנֶנּוּ",
        root: "כונ",
        binyan: "Polel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיְכוֹנְנֶהָ",
        root: "כונ",
        binyan: "Polel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיְכוֹנְנוּ",
        root: "כונ",
        binyan: "Polel",
        form: "Wayyiqtol",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וַיְכוֹנְנוּנִי",
        root: "כונ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וַיְמֹדֶד",
        root: "מוד",
        binyan: "Polel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיְמֹתְתֵהוּ",
        root: "מות",
        binyan: "Polel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיְעֹלְלֻהוּ",
        root: "עלל",
        binyan: "Poel",
        form: "Wayyiqtol",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וַיְפַצְפְּצֵנִי",
        root: "פוצ",
        binyan: "Pilpel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיְפַרְפְּרֵנִי",
        root: "פרר",
        binyan: "Pilpel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיְקֹנֵן",
        root: "קינ",
        binyan: "Polel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיְקוֹנֵן",
        root: "קינ",
        binyan: "Polel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיְרֹצְצוּ",
        root: "רצצ",
        binyan: "Poel",
        form: "Wayyiqtol",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וַיִּשְׁתַּחֲוֶה",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיִּשְׁתַּחֲוֻּ",
        root: "שחה",
        binyan: "Hithpael",
        form: "Wayyiqtol",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וַיִּשְׁתַּחֲוּוּ",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Wayyiqtol",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וַיִּשְׁתַּחֲוּוּ",
        root: "שחה",
        binyan: "Hithpael",
        form: "Wayyiqtol",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וַיִּשְׁתָּחוּ",
        root: "שחה",
        binyan: "Hithpael",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיִּשְׁתּוֹמֵם",
        root: "שממ",
        binyan: "Hithpolel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיִּתְגֹּדְדוּ",
        root: "גדד",
        binyan: "Hithpolel",
        form: "Wayyiqtol",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וַיִּתְהֹלֵל",
        root: "הלל",
        binyan: "Hithpolel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיִּתְמַהְמָהּ",
        root: "מהה",
        binyan: "Hithpalpel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיִּתְמַרְמַר",
        root: "מרר",
        binyan: "Hithpalpel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיִּתְמֹדֵד",
        root: "מדד",
        binyan: "Hithpolel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיִּתְפֹּצְצוּ",
        root: "פוצ",
        binyan: "Hithpolel",
        form: "Wayyiqtol",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וַיִּתְרֹצֲצוּ",
        root: "רצצ",
        binyan: "Hithpolel",
        form: "Wayyiqtol",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "וַנִּתְעוֹדָד",
        root: "עוד",
        binyan: "Hithpolel",
        form: "Wayyiqtol",
        pgn: "1cp",
    },
    IrregularVerb {
        surface: "וַתְּחוֹלֵל",
        root: "חול",
        binyan: "Polel",
        form: "Wayyiqtol",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "וַתְּכוֹנֵן",
        root: "כונ",
        binyan: "Polel",
        form: "Wayyiqtol",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "וַתְּרוֹמֵם",
        root: "רומ",
        binyan: "Polel",
        form: "Wayyiqtol",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "וַתְּשֹׁקְקֶהָ",
        root: "שוק",
        binyan: "Polel",
        form: "Wayyiqtol",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "וַתִּשְׁתַּחֲוֶיןָ",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Wayyiqtol",
        pgn: "3fp",
    },
    IrregularVerb {
        surface: "וַתִּשְׁתָּחוּ",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Wayyiqtol",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "וַתִּתְבֹּנֶן",
        root: "בינ",
        binyan: "Hithpolel",
        form: "Wayyiqtol",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "וַתִּתְחַלְחַל",
        root: "חול",
        binyan: "Hithpalpel",
        form: "Wayyiqtol",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "וָאֲכַלְכְּלֵם",
        root: "כול",
        binyan: "Pilpel",
        form: "Wayyiqtol",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וָאֶשְׁתַּחֲוֶה",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Wayyiqtol",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וָאֶשְׁתּוֹמֵם",
        root: "שממ",
        binyan: "Hithpolel",
        form: "Wayyiqtol",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וָאֶתְבּוֹנֵן",
        root: "בינ",
        binyan: "Hithpolel",
        form: "Wayyiqtol",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וָאֶתְקוֹטָטָה",
        root: "קוט",
        binyan: "Hithpolel",
        form: "Wayyiqtol",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וּלְהִשְׁתַּחֲות",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "וּלְכַלְכֵּל",
        root: "כול",
        binyan: "Pilpel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "וּמְכַרְכֵּר",
        root: "כרר",
        binyan: "Pilpel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "וּמְצַפְצֵף",
        root: "צפפ",
        binyan: "Pilpel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "וּמְרוֹמַם",
        root: "רומ",
        binyan: "Polal",
        form: "Participle (pas.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "וּמְשֹׁרֲרוֹת",
        root: "שיר",
        binyan: "Polel",
        form: "Participle (act.)",
        pgn: "fp",
    },
    IrregularVerb {
        surface: "וּמִשְׁתַּחֲוֶה",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "וּמִתְגֹּדְדִים",
        root: "גדד",
        binyan: "Hithpoel",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        surface: "וּמִתְקוֹמְמִי",
        root: "לבב",
        binyan: "Hithpolel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "וּמִתַּעְתְּעִים",
        root: "תעע",
        binyan: "Hithpalpel",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        surface: "וּמוֹתְתֵנִי",
        root: "מות",
        binyan: "Polel",
        form: "Imperative",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "וּנְרוֹמְמָה",
        root: "רומ",
        binyan: "Polel",
        form: "Cohortative",
        pgn: "1cp",
    },
    IrregularVerb {
        surface: "וּתְחוֹלֵל",
        root: "חול",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "וּתְכוֹנֵן",
        root: "כונ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "וּתְמֹגְגֵנִי",
        root: "מוג",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "וּתְרוֹמְמֶךָּ",
        root: "רומ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "חֳמַרְמְרוּ",
        root: "חמר",
        binyan: "Pealal",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "חֳמַרְמָרוּ",
        root: "חמר",
        binyan: "Pealal",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "חֹלֲלָה",
        root: "חלל",
        binyan: "Poel",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "חוֹלָלְתִּי",
        root: "חול",
        binyan: "Polal",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "חוֹלָלְתָּ",
        root: "חול",
        binyan: "Polal",
        form: "Perfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "יְבוֹנְנֵהוּ",
        root: "בינ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְהוֹלֵל",
        root: "הלל",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְחֹנֵנוּ",
        root: "חננ",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יְחֹקְקוּ",
        root: "חקק",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יְחוֹלֵל",
        root: "חול",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְחוֹלָלוּ",
        root: "חול",
        binyan: "Polal",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יְכַלְכְּלֶךָ",
        root: "כול",
        binyan: "Pilpel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְכַלְכְּלֻהוּ",
        root: "כול",
        binyan: "Pilpel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְכַלְכְּלוּךָ",
        root: "כול",
        binyan: "Pilpel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יְכַלְכֵּל",
        root: "כול",
        binyan: "Pilpel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        // Quadriliteral root כרסם "devour" (Ps 80:14); the triliteral generator
        // cannot model a four-radical root. + 3fs object suffix in the surface.
        surface: "יְכַרְסְמֶנָּה",
        root: "כרסם",
        binyan: "Piel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְכוֹנְנֶהָ",
        root: "כונ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְכוֹנֵן",
        root: "כונ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְמוֹלֵל",
        root: "מול",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְנֹפֵף",
        root: "נופ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְנוֹבֵב",
        root: "נוב",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְסַכְסֵךְ",
        root: "סוכ",
        binyan: "Pilpel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְסֹבְבֵנִי",
        root: "סבב",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְסֹבְבֶנְהוּ",
        root: "סבב",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְסֹעֵר",
        root: "סער",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְסוֹבְבֶנּוּ",
        root: "סבב",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְסוֹבְבֻהָ",
        root: "סבב",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יְעֹעֵרוּ",
        root: "עור",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יְעוֹדֵד",
        root: "עוד",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְעוֹלְלוּ",
        root: "עלל",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יְעוֹפֵף",
        root: "עופ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְפֹצֵץ",
        root: "פוצ",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְקוֹמֵם",
        root: "לבב",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְקוֹמֵמוּ",
        root: "לבב",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יְקוֹסֵס",
        root: "קסס",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְרֹעָע",
        root: "רוע",
        binyan: "Polal",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְרֹשֵׁשׁ",
        root: "רשש",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְרוֹמְמֵנִי",
        root: "רומ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְרוֹמֵם",
        root: "רומ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְרוֹפָפוּ",
        root: "רפפ",
        binyan: "Poal",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יְרוֹצֵצוּ",
        root: "רוצ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יְשַׁעַשְׁעוּ",
        root: "שעע",
        binyan: "Pilpel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יְשֹׁדֵד",
        root: "שדד",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְשֹׁטְטוּ",
        root: "שוט",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יְשׁוֹבֵב",
        root: "שוב",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יְשׁוֹטְטוּ",
        root: "שוט",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יְשׁוֹרֵר",
        root: "שיר",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יִּתְאוֹנֵן",
        root: "אננ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יִשְׁתַּחֲוֶה",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יִשְׁתַּחֲוּוּ",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יִשְׁתַּקְשְׁקוּן",
        root: "שקק",
        binyan: "Hithpalpel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יִשְׁתּוֹמֵם",
        root: "שממ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יִתְבֹּשָׁשׁוּ",
        root: "בוש",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יִתְבּוֹלָל",
        root: "בלל",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יִתְבּוֹנָן",
        root: "בינ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יִתְבּוֹנָנוּ",
        root: "בינ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יִתְגֹּדַד",
        root: "גדד",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יִתְגֹּדָדוּ",
        root: "גדד",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יִתְגֹּעֲשׁוּ",
        root: "געש",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יִתְגּוֹרָרוּ",
        root: "גור",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יִתְהוֹלְלוּ",
        root: "הלל",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יִתְכּוֹנָן",
        root: "כונ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יִתְלוֹנָן",
        root: "לונ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יִתְמַהְמָהּ",
        root: "מהה",
        binyan: "Hithpalpel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יִתְנֹדֲדוּ",
        root: "נדד",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יִתְעֹרָר",
        root: "עור",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יִתְעוֹפֵף",
        root: "עופ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יִתְרוֹעֲעוּ",
        root: "רוע",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יַשְׁחֶנָּה",
        root: "שחה",
        binyan: "Hiphil",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יָפְיָפִיתָ",
        root: "יפה",
        binyan: "Pealal",
        form: "Perfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "יוֹדַעְתִּי",
        root: "ידע",
        binyan: "Poel",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "כְּמִתְאֹנְנִים",
        root: "אננ",
        binyan: "Hithpolel",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        surface: "כְּמִתְלַהְלֵהַּ",
        root: "להה",
        binyan: "Hithpalpel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "כִּלְכַּלְתָּם",
        root: "כול",
        binyan: "Pilpel",
        form: "Perfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "כִּמְתַעְתֵּעַ",
        root: "תעע",
        binyan: "Pilpel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "כוֹנַנְתָּהּ",
        root: "כונ",
        binyan: "Polel",
        form: "Perfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "לְהִשְׁתַּחֲות",
        root: "שחה",
        binyan: "Hithpael",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "לְהִתְגֹּלֵל",
        root: "גלל",
        binyan: "Hithpolel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "לְהִתְמַהְמֵהַּ",
        root: "מהה",
        binyan: "Hithpalpel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "לְהִתְנוֹסֵס",
        root: "נוס",
        binyan: "Hithpolel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "לְהִתְעוֹלֵל",
        root: "עלל",
        binyan: "Hithpolel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "לְהִתְרֹעֵעַ",
        root: "רעע",
        binyan: "Hithpolel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "לְחַרְחַר",
        root: "חרר",
        binyan: "Pilpel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "לְכַלְכְּלֶךָ",
        root: "כול",
        binyan: "Pilpel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "לְכַלְכֵּל",
        root: "כול",
        binyan: "Pilpel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "לְכַלְכֶּלְךָ",
        root: "כול",
        binyan: "Pilpel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "מְגוֹלָלָה",
        root: "גלל",
        binyan: "Poal",
        form: "Participle (pas.)",
        pgn: "fs",
    },
    IrregularVerb {
        surface: "מְהוֹלָל",
        root: "הלל",
        binyan: "Poal",
        form: "Participle (pas.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מְהוֹלָלַי",
        root: "הלל",
        binyan: "Poal",
        form: "Participle (pas.)",
        pgn: "mp",
    },
    IrregularVerb {
        surface: "מְזַעְזְעֶיךָ",
        root: "זוע",
        binyan: "Pilpel",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        surface: "מְחֹלְלֶךָ",
        root: "חול",
        binyan: "Polel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מְחֹלָל",
        root: "חלל",
        binyan: "Polal",
        form: "Participle (pas.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מְטַלְטֶלְךָ",
        root: "טול",
        binyan: "Pilpel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מְכַלְכֵּל",
        root: "כול",
        binyan: "Pilpel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מְכַרְכֵּר",
        root: "כרר",
        binyan: "Pilpel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        // Quadriliteral root כרבל "wrap/robe" (1 Chr 15:27), Pual passive
        // participle; a four-radical root the triliteral generator cannot model.
        surface: "מְכֻרְבָּל",
        root: "כרבל",
        binyan: "Pual",
        form: "Participle (pas.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מְקַרְקַר",
        root: "קור",
        binyan: "Pilpel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מְשֹׁרֲרִים",
        root: "שיר",
        binyan: "Polel",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        surface: "מִּמִתְקוֹמְמַי",
        root: "לבב",
        binyan: "Hithpolel",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        surface: "מִמִּתְקוֹמְמִים",
        root: "לבב",
        binyan: "Hithpolel",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        surface: "מִסְתּוֹלֵל",
        root: "סלל",
        binyan: "Hithpolel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מִשְׁתַּחֲוִיתֶם",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        surface: "מִתְבּוֹסֶסֶת",
        root: "בוס",
        binyan: "Hithpolel",
        form: "Participle (act.)",
        pgn: "fs",
    },
    IrregularVerb {
        surface: "מִתְגֹּלֵל",
        root: "גלל",
        binyan: "Hithpolel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מִתְגּוֹרֵר",
        root: "גור",
        binyan: "Hithpolel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מִתְגּוֹרֵר",
        root: "גרר",
        binyan: "Hithpolel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מִתְחוֹלֵל",
        root: "חול",
        binyan: "Hithpolel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מִתְמַהְמֵהַּ",
        root: "מהה",
        binyan: "Hithpalpel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מִתְנוֹדֵד",
        root: "נוד",
        binyan: "Hithpolel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מִתְנוֹסְסוֹת",
        root: "נסס",
        binyan: "Hithpolel",
        form: "Participle (act.)",
        pgn: "fp",
    },
    IrregularVerb {
        surface: "מִתְעוֹרֵר",
        root: "עור",
        binyan: "Hithpolel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מִתְקוֹמָמָה",
        root: "לבב",
        binyan: "Hithpolel",
        form: "Participle (act.)",
        pgn: "fs",
    },
    IrregularVerb {
        surface: "מִתְרוֹנֵן",
        root: "רונ",
        binyan: "Hithpolel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מִתְרוֹשֵׁשׁ",
        root: "רוש",
        binyan: "Hithpolel",
        form: "Participle (act.)",
        pgn: "ms",
    },
    IrregularVerb {
        surface: "מוֹתְתַנִי",
        root: "מות",
        binyan: "Polel",
        form: "Perfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "נִשְׁתַּחֲוֶה",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Imperfect",
        pgn: "1cp",
    },
    IrregularVerb {
        surface: "נִשְׁתַּחֲוֶה",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Cohortative",
        pgn: "1cp",
    },
    IrregularVerb {
        surface: "נִשְׁתָּוָה",
        root: "שוה",
        binyan: "Nithpael",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "סְחַרְחַר",
        root: "סחר",
        binyan: "Pealal",
        form: "Perfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "סַלְסְלֶהָ",
        root: "סלל",
        binyan: "Pilpel",
        form: "Imperative",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "עַרְעֵר",
        root: "ערר",
        binyan: "Pilpel",
        form: "Inf. Absolute",
        pgn: "",
    },
    IrregularVerb {
        surface: "עֹנְנֵיכֶם",
        root: "עננ",
        binyan: "Poel",
        form: "Participle (act.)",
        pgn: "mp",
    },
    IrregularVerb {
        surface: "עוֹלְלָה",
        root: "עלל",
        binyan: "Poel",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "עוֹלַל",
        root: "עלל",
        binyan: "Poal",
        form: "Perfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "עוֹלַלְתָּ",
        root: "עלל",
        binyan: "Poel",
        form: "Perfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "פַּרְשֵׁז",
        root: "פרש",
        binyan: "Pilel",
        form: "Inf. Absolute",
        pgn: "",
    },
    IrregularVerb {
        surface: "צִמְּתוּתֻנִי",
        root: "צמת",
        binyan: "Pilpel",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "קִלְקַל",
        root: "קלל",
        binyan: "Pilpel",
        form: "Perfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "רַעֲנָנָה",
        root: "רענ",
        binyan: "Palel",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "רֹמְמָתְהוּ",
        root: "רומ",
        binyan: "Polel",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "רֻאּוּ",
        root: "ראה",
        binyan: "Qal passive",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "רֻטֲפַשׁ",
        root: "",
        binyan: "Qal passive",
        form: "Perfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "רוֹמְמוּ",
        root: "רומ",
        binyan: "Polel",
        form: "Imperative",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "רוֹמֵמָה",
        root: "רממ",
        binyan: "Polel",
        form: "Participle (act.)",
        pgn: "fs",
    },
    IrregularVerb {
        surface: "שִׁעֲשָׁעְתִּי",
        root: "שעע",
        binyan: "Pilpel",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "שַׁאֲנָנוּ",
        root: "שאנ",
        binyan: "Palel",
        form: "Perfect",
        pgn: "3cp",
    },
    IrregularVerb {
        surface: "שׁוֹבְבָתֶךְ",
        root: "שוב",
        binyan: "Polel",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "תְּהוֹתְתוּ",
        root: "הות",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "תְּחוֹלֵל",
        root: "חול",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "תְּחוֹלֶלְכֶם",
        root: "חול",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "תְּכוֹנֵן",
        root: "כונ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "תְּמֹגְגֶנָּה",
        root: "מוג",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "תְּמוֹתֵת",
        root: "מות",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "תְּסֹכְכֵנִי",
        root: "סוכ",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "תְּסוֹבְבֵנִי",
        root: "סבב",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "תְּסוֹבְבֶךָּ",
        root: "סבב",
        binyan: "Poel",
        form: "Jussive",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "תְּסוֹבֵב",
        root: "סבב",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "תְּעוֹרֵר",
        root: "עור",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "תְּצַפְצֵף",
        root: "צפפ",
        binyan: "Pilpel",
        form: "Imperfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "תְּצוֹדֵדְנָה",
        root: "צוד",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "2fp",
    },
    IrregularVerb {
        surface: "תְּקוֹמֵם",
        root: "לבב",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "תְּקוֹנֵנָּה",
        root: "קינ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3fp",
    },
    IrregularVerb {
        surface: "תְּרוֹמְמֵנִי",
        root: "רומ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "תְּרוֹמַמְנָה",
        root: "רומ",
        binyan: "Polal",
        form: "Imperfect",
        pgn: "3fp",
    },
    IrregularVerb {
        surface: "תְּשַׂגְשֵׂגִי",
        root: "סוג",
        binyan: "Pilpel",
        form: "Imperfect",
        pgn: "2fs",
    },
    IrregularVerb {
        surface: "תְּשָׁעֳשָׁעוּ",
        root: "שעע",
        binyan: "Polpal",
        form: "Imperfect",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "תְּשׁוֹבֵב",
        root: "שוב",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "תְּתַחֲרֶה",
        root: "חרה",
        binyan: "Tiphil",
        form: "Imperfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "תְעוֹלֵל",
        root: "עלל",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "תְעוֹנֵנוּ",
        root: "עננ",
        binyan: "Poel",
        form: "Imperfect",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "תְרֹמֵם",
        root: "רומ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "תְרוֹמֵם",
        root: "רומ",
        binyan: "Polel",
        form: "Imperfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "תִּכּוֹנָנִי",
        root: "כונ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "2fs",
    },
    IrregularVerb {
        surface: "תִּשְׁתּוֹחֲחִי",
        root: "שחח",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "2fs",
    },
    IrregularVerb {
        surface: "תִּשּׁוֹמֵם",
        root: "שממ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "תִּתְבֹּנָנוּ",
        root: "בינ",
        binyan: "Hithpolel",
        form: "Jussive",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "תִּתְבּוֹנְנוּ",
        root: "בינ",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "תִּתְגֹּדְדִי",
        root: "גדד",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "2fs",
    },
    IrregularVerb {
        surface: "תִּתְגּוֹדָדִי",
        root: "גדד",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "2fs",
    },
    IrregularVerb {
        surface: "תִּתְלוֹצָצוּ",
        root: "ליצ",
        binyan: "Hithpolel",
        form: "Jussive",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "תִּתְמוֹגַגְנָה",
        root: "מוג",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3fp",
    },
    IrregularVerb {
        surface: "תִּתְנוֹדָד",
        root: "נוד",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "תִּתְעַרְעָר",
        root: "ערר",
        binyan: "Hithpalpel",
        form: "Imperfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "תִרְגַּלְתִּי",
        root: "רגל",
        binyan: "Tiphil",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "תִשְׁתַּחֲוֶה",
        root: "שחה",
        binyan: "Hishtaphel",
        form: "Imperfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "תִשְׁתּוֹחָח",
        root: "שחח",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "תִתְגֹּדְדוּ",
        root: "גדד",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "תִתְמוֹגָג",
        root: "מוג",
        binyan: "Hithpolel",
        form: "Imperfect",
        pgn: "3fs",
    },
    // Suppletive היה / חיה (Strong 1961/2421): aleph-preformative & apocopated
    // wayyiqtol (וָאֱהִי, וַיֶּהִי), doubly-weak Niphal (נִהְיְתָה), paragogic-nun
    // imperfects (תִּהְיֶיןָ) — forms the triliteral generator cannot produce.
    IrregularVerb {
        surface: "הֱיוּ",
        root: "היה",
        binyan: "Qal",
        form: "Imperative",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "הֶחֱיִתָנוּ",
        root: "חיה",
        binyan: "Hiphil",
        form: "Perfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "הַחֲיִתֶם",
        root: "חיה",
        binyan: "Hiphil",
        form: "Perfect",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "הָיִיתְ",
        root: "היה",
        binyan: "Qal",
        form: "Perfect",
        pgn: "2fs",
    },
    IrregularVerb {
        surface: "הָיוֹ",
        root: "היה",
        binyan: "Qal",
        form: "Inf. Absolute",
        pgn: "",
    },
    IrregularVerb {
        surface: "וְהַחֲיִתֶם",
        root: "חיה",
        binyan: "Hiphil",
        form: "Perfect",
        pgn: "2mp",
    },
    IrregularVerb {
        surface: "וְהָיִיתְ",
        root: "היה",
        binyan: "Qal",
        form: "Perfect",
        pgn: "2fs",
    },
    IrregularVerb {
        surface: "וְהָיִתָ",
        root: "היה",
        binyan: "Qal",
        form: "Perfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "וְהָיִתָה",
        root: "היה",
        binyan: "Qal",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "וְחָיִתָה",
        root: "חיה",
        binyan: "Qal",
        form: "Perfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "וְיֶחִי",
        root: "חיה",
        binyan: "Qal",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וְלִהְיֹתְךָ",
        root: "היה",
        binyan: "Qal",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "וְלִהְיוֹת",
        root: "היה",
        binyan: "Qal",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "וְנִהְיָתָה",
        root: "היה",
        binyan: "Niphal",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "וְתִהְיֶנָה",
        root: "היה",
        binyan: "Qal",
        form: "Jussive",
        pgn: "3fp",
    },
    IrregularVerb {
        surface: "וִיחַיֵּהוּ",
        root: "חיה",
        binyan: "Piel",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וֶחְיֵה",
        root: "חיה",
        binyan: "Qal",
        form: "Imperative",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "וַיְחַיֶּהָ",
        root: "חיה",
        binyan: "Piel",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיֶּהִי",
        root: "היה",
        binyan: "Qal",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַיֶּחִי",
        root: "חיה",
        binyan: "Qal",
        form: "Wayyiqtol",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "וַתְּחַיֶּיןָ",
        root: "חיה",
        binyan: "Piel",
        form: "Wayyiqtol",
        pgn: "3fp",
    },
    IrregularVerb {
        surface: "וַתְּחַיֶּיןָ",
        root: "חיה",
        binyan: "Piel",
        form: "Wayyiqtol",
        pgn: "2fp",
    },
    IrregularVerb {
        surface: "וַתִּהְיֶיןָ",
        root: "היה",
        binyan: "Qal",
        form: "Wayyiqtol",
        pgn: "3fp",
    },
    IrregularVerb {
        surface: "וַתִּהְיֶנָה",
        root: "היה",
        binyan: "Qal",
        form: "Wayyiqtol",
        pgn: "3fp",
    },
    IrregularVerb {
        surface: "וַתֶּהִי",
        root: "היה",
        binyan: "Qal",
        form: "Wayyiqtol",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "וָאֱהִי",
        root: "היה",
        binyan: "Qal",
        form: "Wayyiqtol",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "וּלְהַחֲיוֹת",
        root: "חיה",
        binyan: "Hiphil",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "וּלְחַיּוֹתָם",
        root: "חיה",
        binyan: "Piel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "חִיָּתְנִי",
        root: "חיה",
        binyan: "Piel",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "חַיֵּיהוּ",
        root: "חיה",
        binyan: "Piel",
        form: "Imperative",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "חָיוֹ",
        root: "חיה",
        binyan: "Qal",
        form: "Inf. Absolute",
        pgn: "",
    },
    IrregularVerb {
        surface: "יִּהְיֶה",
        root: "היה",
        binyan: "Qal",
        form: "Imperfect",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "יִּהְיוּ",
        root: "היה",
        binyan: "Qal",
        form: "Imperfect",
        pgn: "3mp",
    },
    IrregularVerb {
        surface: "יֶהִי",
        root: "היה",
        binyan: "Qal",
        form: "Jussive",
        pgn: "3ms",
    },
    IrregularVerb {
        surface: "לְחַיּוֹתָם",
        root: "חיה",
        binyan: "Piel",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "לִחְיוֹת",
        root: "חיה",
        binyan: "Qal",
        form: "Inf. Construct",
        pgn: "",
    },
    IrregularVerb {
        surface: "נִּהְיָתָה",
        root: "היה",
        binyan: "Niphal",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "נִהְיְתָה",
        root: "היה",
        binyan: "Niphal",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "נִהְיֵיתִי",
        root: "היה",
        binyan: "Niphal",
        form: "Perfect",
        pgn: "1cs",
    },
    IrregularVerb {
        surface: "נִהְיֵיתָ",
        root: "היה",
        binyan: "Niphal",
        form: "Perfect",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "נִהְיָתָה",
        root: "היה",
        binyan: "Niphal",
        form: "Perfect",
        pgn: "3fs",
    },
    IrregularVerb {
        surface: "תִּהְיֵה",
        root: "היה",
        binyan: "Qal",
        form: "Jussive",
        pgn: "2ms",
    },
    IrregularVerb {
        surface: "תִּהְיֶין",
        root: "היה",
        binyan: "Qal",
        form: "Imperfect",
        pgn: "3fp",
    },
    IrregularVerb {
        surface: "תִּהְיֶיןָ",
        root: "היה",
        binyan: "Qal",
        form: "Imperfect",
        pgn: "3fp",
    },
    IrregularVerb {
        surface: "תִהְיֶיןָ",
        root: "היה",
        binyan: "Qal",
        form: "Imperfect",
        pgn: "3fp",
    },
];
