[package]
name = "haqor-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Command-line tools for Haqor"
repository.workspace = true

[[bin]]
name = "haqor"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.42", features = ["derive"] }
env_logger = "0.11.5"
haqor-admin = { path = "../haqor-admin", version = "0.7.5" }
haqor-core = { path = "../haqor-core", version = "0.7.5" }
haqor-db-gen = { path = "../haqor-db-gen", version = "0.7.5" }
haqor-sync-server = { path = "../haqor-sync-server", version = "0.7.5" }
log = "0.4.22"
