name: Cargo Build & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    environment: cargo

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Cache
        id: cache-publish-action
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose

      - name: Login into crates.io
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Build binaries in "release" mode
        run: cargo build -r
      - name: "Package for crates.io"
        run: cargo package # publishes a package as a tarball

      - name: "Publish to crates.io"
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: cargo publish
